"""add_dailyreport_starpoint_models

Revision ID: 34c984481f64
Revises: 4a3f7841bc70
Create Date: 2026-07-17 11:24:07.435375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '34c984481f64'
down_revision: Union[str, Sequence[str], None] = '4a3f7841bc70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailyreport',
    sa.Column('today_hours', sa.Float(), nullable=False),
    sa.Column('current_stage', sa.Enum('DEVELOPING', 'TESTING', 'COMPLETED', 'PAUSED', name='reportstage'), nullable=False),
    sa.Column('progress', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('completion_judgment', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('starpoint_change', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('has_blocker', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engineer_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('report_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['engineer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('starpointrecord',
    sa.Column('change_amount', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('judgment_type', sa.Enum('MANUAL', 'AUTO_RATIO', 'AUTO_THRESHOLD', name='judgmenttype'), nullable=False),
    sa.Column('T_reported', sa.Float(), nullable=True),
    sa.Column('T_actual', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engineer_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['engineer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('starpointrecord')
    op.drop_table('dailyreport')
    # ### end Alembic commands ###
