"""add_audit_log_model

Revision ID: 5eaf5b5ed768
Revises: 9a9b330a65e1
Create Date: 2026-07-18 17:14:30.380928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eaf5b5ed768'
down_revision: Union[str, Sequence[str], None] = '9a9b330a65e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditlog',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('task', sa.Column('progress', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'progress')
    op.drop_table('auditlog')
    # ### end Alembic commands ###
