"""add_task_T_effective_field

Revision ID: 73adfb52d306
Revises: 6b6522a1db4f
Create Date: 2026-07-25 12:10:42.108318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73adfb52d306'
down_revision: Union[str, Sequence[str], None] = '6b6522a1db4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('T_effective', sa.Float(), nullable=True))
    op.drop_column('user', 'baseline_client_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('baseline_client_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('task', 'T_effective')
    # ### end Alembic commands ###
