"""add_expected_online_time_and_T_reported_complete_time

Revision ID: 7b6caede1dfd
Revises: 2a89fe45b02c
Create Date: 2026-07-20 12:58:55.528095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b6caede1dfd'
down_revision: Union[str, Sequence[str], None] = '2a89fe45b02c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('expected_online_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('task', sa.Column('T_reported_complete_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'T_reported_complete_time')
    op.drop_column('task', 'expected_online_time')
    # ### end Alembic commands ###
