"""add_client_resource_system_rule_models

Revision ID: 9a9b330a65e1
Revises: 34c984481f64
Create Date: 2026-07-17 11:33:19.309748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9a9b330a65e1'
down_revision: Union[str, Sequence[str], None] = '34c984481f64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('systemrule',
    sa.Column('category', sa.Enum('STARPOINT_REWARD', 'SALARY_FORMULA', 'CLIENT_RESOURCE', 'COMPLETION_JUDGMENT', 'SYSTEM_PARAM', name='rulecategory'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('applies_to', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientresource',
    sa.Column('actual_count', sa.Integer(), nullable=False),
    sa.Column('baseline_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pm_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pm_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clientresource')
    op.drop_table('systemrule')
    # ### end Alembic commands ###
