"""add_user_hr_fields_plus_admin_delete

Revision ID: c572b59f57ba
Revises: 7b6caede1dfd
Create Date: 2026-07-22 10:40:16.528765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c572b59f57ba'
down_revision: Union[str, Sequence[str], None] = '7b6caede1dfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('user', sa.Column('department', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('user', sa.Column('hire_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user', sa.Column('employment_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'employment_status')
    op.drop_column('user', 'hire_date')
    op.drop_column('user', 'department')
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###
