"""add_task_T_estimate_field

Revision ID: e9a4b5c70100
Revises: 73adfb52d306
Create Date: 2026-08-06 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9a4b5c70100'
down_revision: Union[str, Sequence[str], None] = '73adfb52d306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('T_estimate', sa.Float(), nullable=True))
    # end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'T_estimate')
    # end Alembic commands ###
