"""prefix tables with tpl_

Revision ID: ef23d6423156
Revises: 3110d5473bd1
Create Date: 2026-09-01 19:57:36.929581

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'ef23d6423156'
down_revision: Union[str, Sequence[str], None] = '3110d5473bd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    如果旧表（user/role/userrole/role_scope）存在，先迁移数据再删除，避免数据丢失。
    对于全新数据库，直接创建 tpl_ 前缀表。
    """
    # ### commands auto generated by Alembic - please adjust! ###

    # === 1. 创建 tpl_ 前缀表 ===
    op.create_table('tpl_role',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tpl_role_name'), 'tpl_role', ['name'], unique=True)
    op.create_table('tpl_user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tpl_user_email'), 'tpl_user', ['email'], unique=True)
    op.create_table('tpl_role_scope',
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['tpl_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tpl_user_role',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['tpl_role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['tpl_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )

    # === 2. 迁移旧表数据（如果旧表存在）===
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = set(inspector.get_table_names())

    if 'role' in existing_tables:
        # role → tpl_role
        conn.execute(sa.text(
            "INSERT INTO tpl_role (id, name, created_at) "
            "SELECT id, name, created_at FROM role"
        ))
    if 'user' in existing_tables:
        # user → tpl_user
        conn.execute(sa.text(
            "INSERT INTO tpl_user (id, email, is_active, is_superuser, full_name, hashed_password, created_at) "
            "SELECT id, email, is_active, is_superuser, full_name, hashed_password, created_at FROM user"
        ))
    if 'role_scope' in existing_tables:
        # role_scope → tpl_role_scope
        conn.execute(sa.text(
            "INSERT INTO tpl_role_scope (id, scope, role_id, created_at) "
            "SELECT id, scope, role_id, created_at FROM role_scope"
        ))
    if 'userrole' in existing_tables:
        # userrole → tpl_user_role
        conn.execute(sa.text(
            "INSERT INTO tpl_user_role (user_id, role_id) "
            "SELECT user_id, role_id FROM userrole"
        ))

    # === 3. 删除旧表（顺序：先子表，再父表）===
    if 'userrole' in existing_tables:
        op.drop_table('userrole')
    if 'role_scope' in existing_tables:
        op.drop_table('role_scope')
    if 'user' in existing_tables:
        op.drop_index(op.f('ix_user_email'), table_name='user')
        op.drop_table('user')
    if 'role' in existing_tables:
        op.drop_index(op.f('ix_role_name'), table_name='role')
        op.drop_table('role')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_scope',
    sa.Column('scope', sa.VARCHAR(length=100), nullable=False),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('role_id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=1)
    op.create_table('user',
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_superuser', sa.BOOLEAN(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=1)
    op.create_table('userrole',
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('role_id', sa.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.drop_table('tpl_user_role')
    op.drop_table('tpl_role_scope')
    op.drop_index(op.f('ix_tpl_user_email'), table_name='tpl_user')
    op.drop_table('tpl_user')
    op.drop_index(op.f('ix_tpl_role_name'), table_name='tpl_role')
    op.drop_table('tpl_role')
    # ### end Alembic commands ###
