"""add pm_name and engineer_name to task

Revision ID: f229af67f56e
Revises: 0166694dc42f
Create Date: 2026-07-24 08:29:23.964555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f229af67f56e'
down_revision: Union[str, Sequence[str], None] = '0166694dc42f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('pm_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False, server_default=''))
    op.add_column('task', sa.Column('engineer_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'engineer_name')
    op.drop_column('task', 'pm_name')
    # ### end Alembic commands ###
