"""add_user_role_and_salary_fields

Revision ID: fd0e5ee71918
Revises: db14db305daa
Create Date: 2026-07-17 10:51:04.265758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd0e5ee71918'
down_revision: Union[str, Sequence[str], None] = 'db14db305daa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 创建枚举类型
    userroletype_enum = sa.Enum('ENGINEER', 'PM', 'ADMIN', name='userroletype')
    userroletype_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('user', sa.Column('role', userroletype_enum, nullable=False, server_default='ENGINEER'))
    op.add_column('user', sa.Column('S0', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('H0', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('T_monthly_plan', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('current_starpoint', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user', sa.Column('S_base', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('S_assess', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('R_base', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('R_assess', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('baseline_client_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'baseline_client_count')
    op.drop_column('user', 'R_assess')
    op.drop_column('user', 'R_base')
    op.drop_column('user', 'S_assess')
    op.drop_column('user', 'S_base')
    op.drop_column('user', 'current_starpoint')
    op.drop_column('user', 'T_monthly_plan')
    op.drop_column('user', 'H0')
    op.drop_column('user', 'S0')
    op.drop_column('user', 'role')

    # 删除枚举类型
    userroletype_enum = sa.Enum('ENGINEER', 'PM', 'ADMIN', name='userroletype')
    userroletype_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
