// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen.js';
import { createRoleV1RolesPost, createUserV1UsersPost, deleteRoleV1RolesRoleIdDelete, deleteUserMeV1UsersMeDelete, deleteUserV1UsersUserIdDelete, healthCheckV1HealthCheckGet, loginAccessTokenV1LoginAccessTokenPost, type Options, readRolesV1RolesGet, readRoleV1RolesRoleIdGet, readUserByIdV1UsersUserIdGet, readUserMeV1UsersMeGet, readUsersV1UsersGet, registerUserV1UsersSignupPost, testTokenV1LoginTestTokenPost, updatePasswordMeV1UsersMePasswordPatch, updateRoleV1RolesRoleIdPatch, updateUserMeV1UsersMePatch, updateUserV1UsersUserIdPatch } from '../sdk.gen.js';
import type { CreateRoleV1RolesPostData, CreateRoleV1RolesPostError, CreateRoleV1RolesPostResponse, CreateUserV1UsersPostData, CreateUserV1UsersPostError, CreateUserV1UsersPostResponse, DeleteRoleV1RolesRoleIdDeleteData, DeleteRoleV1RolesRoleIdDeleteError, DeleteRoleV1RolesRoleIdDeleteResponse, DeleteUserMeV1UsersMeDeleteData, DeleteUserMeV1UsersMeDeleteResponse, DeleteUserV1UsersUserIdDeleteData, DeleteUserV1UsersUserIdDeleteError, DeleteUserV1UsersUserIdDeleteResponse, HealthCheckV1HealthCheckGetData, HealthCheckV1HealthCheckGetResponse, LoginAccessTokenV1LoginAccessTokenPostData, LoginAccessTokenV1LoginAccessTokenPostError, LoginAccessTokenV1LoginAccessTokenPostResponse, ReadRolesV1RolesGetData, ReadRolesV1RolesGetError, ReadRolesV1RolesGetResponse, ReadRoleV1RolesRoleIdGetData, ReadRoleV1RolesRoleIdGetError, ReadRoleV1RolesRoleIdGetResponse, ReadUserByIdV1UsersUserIdGetData, ReadUserByIdV1UsersUserIdGetError, ReadUserByIdV1UsersUserIdGetResponse, ReadUserMeV1UsersMeGetData, ReadUserMeV1UsersMeGetResponse, ReadUsersV1UsersGetData, ReadUsersV1UsersGetError, ReadUsersV1UsersGetResponse, RegisterUserV1UsersSignupPostData, RegisterUserV1UsersSignupPostError, RegisterUserV1UsersSignupPostResponse, TestTokenV1LoginTestTokenPostData, TestTokenV1LoginTestTokenPostResponse, UpdatePasswordMeV1UsersMePasswordPatchData, UpdatePasswordMeV1UsersMePasswordPatchError, UpdatePasswordMeV1UsersMePasswordPatchResponse, UpdateRoleV1RolesRoleIdPatchData, UpdateRoleV1RolesRoleIdPatchError, UpdateRoleV1RolesRoleIdPatchResponse, UpdateUserMeV1UsersMePatchData, UpdateUserMeV1UsersMePatchError, UpdateUserMeV1UsersMePatchResponse, UpdateUserV1UsersUserIdPatchData, UpdateUserV1UsersUserIdPatchError, UpdateUserV1UsersUserIdPatchResponse } from '../types.gen.js';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const healthCheckV1HealthCheckGetQueryKey = (options?: Options<HealthCheckV1HealthCheckGetData>) => createQueryKey('healthCheckV1HealthCheckGet', options);

/**
 * Health Check
 *
 * 健康检查端点，返回 True 表示服务正常运行。
 */
export const healthCheckV1HealthCheckGetOptions = (options?: Options<HealthCheckV1HealthCheckGetData>) => queryOptions<HealthCheckV1HealthCheckGetResponse, DefaultError, HealthCheckV1HealthCheckGetResponse, ReturnType<typeof healthCheckV1HealthCheckGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await healthCheckV1HealthCheckGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthCheckV1HealthCheckGetQueryKey(options)
});

/**
 * Login Access Token
 *
 * OAuth2 兼容的令牌登录：验证邮箱密码，签发访问令牌。
 *
 * 参数：
 * - session：数据库会话
 * - form_data：OAuth2 表单（username=邮箱，password=密码）
 *
 * 返回值：
 * - Token：访问令牌（JWT）
 *
 * 异常：
 * - 400：邮箱或密码错误 / 用户未激活
 */
export const loginAccessTokenV1LoginAccessTokenPostMutation = (options?: Partial<Options<LoginAccessTokenV1LoginAccessTokenPostData>>): UseMutationOptions<LoginAccessTokenV1LoginAccessTokenPostResponse, LoginAccessTokenV1LoginAccessTokenPostError, Options<LoginAccessTokenV1LoginAccessTokenPostData>> => {
    const mutationOptions: UseMutationOptions<LoginAccessTokenV1LoginAccessTokenPostResponse, LoginAccessTokenV1LoginAccessTokenPostError, Options<LoginAccessTokenV1LoginAccessTokenPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await loginAccessTokenV1LoginAccessTokenPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Test Token
 *
 * 校验访问令牌并返回当前用户信息（含权限 scope 列表）。
 *
 * 参数：
 * - session：数据库会话
 * - current_user：当前登录用户（依赖注入）
 *
 * 返回值：
 * - UserPublic：当前用户信息（含 scopes）
 */
export const testTokenV1LoginTestTokenPostMutation = (options?: Partial<Options<TestTokenV1LoginTestTokenPostData>>): UseMutationOptions<TestTokenV1LoginTestTokenPostResponse, DefaultError, Options<TestTokenV1LoginTestTokenPostData>> => {
    const mutationOptions: UseMutationOptions<TestTokenV1LoginTestTokenPostResponse, DefaultError, Options<TestTokenV1LoginTestTokenPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await testTokenV1LoginTestTokenPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const readUsersV1UsersGetQueryKey = (options?: Options<ReadUsersV1UsersGetData>) => createQueryKey('readUsersV1UsersGet', options);

/**
 * Read Users
 *
 * 获取所有用户列表（分页）。
 *
 * 权限：拥有 user:read scope（通过 dependencies 依赖注入强制）。
 *
 * 参数：
 * - session：数据库会话（依赖注入）
 * - pagination：分页参数（page, page_size）
 *
 * 返回值：
 * - UsersPublic：包含 data（用户列表）、count（总数）、page（当前页）、page_size（每页大小）、total_pages（总页数）
 */
export const readUsersV1UsersGetOptions = (options?: Options<ReadUsersV1UsersGetData>) => queryOptions<ReadUsersV1UsersGetResponse, ReadUsersV1UsersGetError, ReadUsersV1UsersGetResponse, ReturnType<typeof readUsersV1UsersGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readUsersV1UsersGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readUsersV1UsersGetQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const readUsersV1UsersGetInfiniteQueryKey = (options?: Options<ReadUsersV1UsersGetData>): QueryKey<Options<ReadUsersV1UsersGetData>> => createQueryKey('readUsersV1UsersGet', options, true);

/**
 * Read Users
 *
 * 获取所有用户列表（分页）。
 *
 * 权限：拥有 user:read scope（通过 dependencies 依赖注入强制）。
 *
 * 参数：
 * - session：数据库会话（依赖注入）
 * - pagination：分页参数（page, page_size）
 *
 * 返回值：
 * - UsersPublic：包含 data（用户列表）、count（总数）、page（当前页）、page_size（每页大小）、total_pages（总页数）
 */
export const readUsersV1UsersGetInfiniteOptions = (options?: Options<ReadUsersV1UsersGetData>) => infiniteQueryOptions<ReadUsersV1UsersGetResponse, ReadUsersV1UsersGetError, InfiniteData<ReadUsersV1UsersGetResponse>, QueryKey<Options<ReadUsersV1UsersGetData>>, number | Pick<QueryKey<Options<ReadUsersV1UsersGetData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ReadUsersV1UsersGetData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await readUsersV1UsersGet({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readUsersV1UsersGetInfiniteQueryKey(options)
});

/**
 * Create User
 *
 * 创建新用户。
 *
 * 权限：拥有 user:create scope。
 *
 * 参数：
 * - session：数据库会话
 * - user_in：用户创建 DTO（包含邮箱、密码等）
 *
 * 返回值：
 * - UserPublic：创建成功的用户信息
 *
 * 业务流程：
 * 1. 检查邮箱是否已存在，存在则返回 409 错误
 * 2. 调用 repository create_user() 创建用户（密码自动哈希，默认分配 viewer 角色）
 */
export const createUserV1UsersPostMutation = (options?: Partial<Options<CreateUserV1UsersPostData>>): UseMutationOptions<CreateUserV1UsersPostResponse, CreateUserV1UsersPostError, Options<CreateUserV1UsersPostData>> => {
    const mutationOptions: UseMutationOptions<CreateUserV1UsersPostResponse, CreateUserV1UsersPostError, Options<CreateUserV1UsersPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createUserV1UsersPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete User Me
 *
 * 删除当前用户自己的账户。
 *
 * 权限：登录用户
 *
 * 参数：
 * - session：数据库会话
 * - current_user：当前登录用户
 *
 * 返回值：
 * - Message：删除成功消息
 *
 * 业务逻辑：
 * 1. 检查当前用户是否为超管，超管不允许自删除（防止误操作导致系统无超管）
 * 2. 使用仓库函数删除用户记录
 * 3. 级联删除会由数据库约束自动处理（User.roles 关联表 userrole 外键为 CASCADE）
 *
 * 异常：
 * - 403：超管不允许删除自己
 */
export const deleteUserMeV1UsersMeDeleteMutation = (options?: Partial<Options<DeleteUserMeV1UsersMeDeleteData>>): UseMutationOptions<DeleteUserMeV1UsersMeDeleteResponse, DefaultError, Options<DeleteUserMeV1UsersMeDeleteData>> => {
    const mutationOptions: UseMutationOptions<DeleteUserMeV1UsersMeDeleteResponse, DefaultError, Options<DeleteUserMeV1UsersMeDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteUserMeV1UsersMeDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const readUserMeV1UsersMeGetQueryKey = (options?: Options<ReadUserMeV1UsersMeGetData>) => createQueryKey('readUserMeV1UsersMeGet', options);

/**
 * Read User Me
 *
 * 获取当前登录用户的信息。
 *
 * 权限：登录用户
 *
 * 参数：
 * - session：数据库会话（用于计算权限 scope）
 * - current_user：当前登录用户（依赖注入）
 *
 * 返回值：
 * - UserPublic：当前用户信息（含 scopes 权限列表）
 *
 * 说明：
 * - scopes 由 get_user_scopes 实时计算（超管返回全部 scope）
 * - 用于前端按 scope 控制导航和页面可见性
 */
export const readUserMeV1UsersMeGetOptions = (options?: Options<ReadUserMeV1UsersMeGetData>) => queryOptions<ReadUserMeV1UsersMeGetResponse, DefaultError, ReadUserMeV1UsersMeGetResponse, ReturnType<typeof readUserMeV1UsersMeGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readUserMeV1UsersMeGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readUserMeV1UsersMeGetQueryKey(options)
});

/**
 * Update User Me
 *
 * 更新当前用户自己的信息。
 *
 * 权限：登录用户（自己的账户）
 *
 * 参数：
 * - session：数据库会话
 * - user_in：用户更新 DTO（full_name、email 可选）
 * - current_user：当前登录用户（依赖注入）
 *
 * 返回值：
 * - UserPublic：更新后的用户信息（含 scopes）
 *
 * 业务逻辑：
 * 1. 若修改邮箱，检查新邮箱是否被其他用户占用
 * 2. 使用 model_dump(exclude_unset=True) 仅获取用户明确设置的字段
 * 3. 使用 sqlmodel_update() 合并更新
 * 4. 提交事务
 *
 * 邮箱冲突处理：
 * - 允许用户更新为自己的原邮箱
 * - 若邮箱被其他用户占用，返回 409 冲突错误
 */
export const updateUserMeV1UsersMePatchMutation = (options?: Partial<Options<UpdateUserMeV1UsersMePatchData>>): UseMutationOptions<UpdateUserMeV1UsersMePatchResponse, UpdateUserMeV1UsersMePatchError, Options<UpdateUserMeV1UsersMePatchData>> => {
    const mutationOptions: UseMutationOptions<UpdateUserMeV1UsersMePatchResponse, UpdateUserMeV1UsersMePatchError, Options<UpdateUserMeV1UsersMePatchData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateUserMeV1UsersMePatch({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update Password Me
 *
 * 修改当前用户自己的密码。
 *
 * 权限：登录用户
 *
 * 参数：
 * - session：数据库会话
 * - body：密码更新 DTO（current_password、new_password）
 * - current_user：当前登录用户
 *
 * 返回值：
 * - Message：成功消息
 *
 * 业务流程：
 * 1. 验证现有密码是否正确（调用 verify_password）
 * 2. 检查新密码是否与旧密码相同（防止无意义操作）
 * 3. 哈希新密码并保存到数据库
 * 4. 返回成功消息
 *
 * 验证失败返回：
 * - 400：密码错误
 * - 400：新密码与旧密码相同
 */
export const updatePasswordMeV1UsersMePasswordPatchMutation = (options?: Partial<Options<UpdatePasswordMeV1UsersMePasswordPatchData>>): UseMutationOptions<UpdatePasswordMeV1UsersMePasswordPatchResponse, UpdatePasswordMeV1UsersMePasswordPatchError, Options<UpdatePasswordMeV1UsersMePasswordPatchData>> => {
    const mutationOptions: UseMutationOptions<UpdatePasswordMeV1UsersMePasswordPatchResponse, UpdatePasswordMeV1UsersMePasswordPatchError, Options<UpdatePasswordMeV1UsersMePasswordPatchData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updatePasswordMeV1UsersMePasswordPatch({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Register User
 *
 * 用户自助注册（无需登录）。
 *
 * 权限：公开
 *
 * 参数：
 * - session：数据库会话
 * - user_in：用户注册 DTO（邮箱、密码、姓名）
 *
 * 返回值：
 * - UserPublic：创建的用户信息
 *
 * 业务流程：
 * 1. 检查邮箱是否已存在
 * 2. 使用 model_validate 将 UserRegister DTO 转换为 UserCreate DTO
 * 3. 调用 repository.create_user() 创建用户
 *
 * 异常：
 * - 409：邮箱已被注册
 *
 * 与 /users POST 的区别：
 * - 此路由无需超管权限，任何人可注册
 * - 此路由不发送邮件通知
 */
export const registerUserV1UsersSignupPostMutation = (options?: Partial<Options<RegisterUserV1UsersSignupPostData>>): UseMutationOptions<RegisterUserV1UsersSignupPostResponse, RegisterUserV1UsersSignupPostError, Options<RegisterUserV1UsersSignupPostData>> => {
    const mutationOptions: UseMutationOptions<RegisterUserV1UsersSignupPostResponse, RegisterUserV1UsersSignupPostError, Options<RegisterUserV1UsersSignupPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await registerUserV1UsersSignupPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete User
 *
 * 删除指定用户（scope 判定，而非超管判定）。
 *
 * 权限：拥有 user:admin 或 user:delete scope（与用户管理删除按钮一致）。
 * - 超管本身拥有全部 scope，天然满足此权限。
 * - 普通拥有 user:delete scope 的角色（如 editor）也可删除用户。
 *
 * 参数：
 * - session：数据库会话
 * - current_user：当前用户（用于禁止删除自己）
 * - user_id：目标用户 UUID
 *
 * 返回值：
 * - Message：删除成功消息
 *
 * 异常：
 * - 404：用户不存在
 * - 403：不允许删除自己
 * - 403：无 user:admin / user:delete scope
 *
 * 注意：
 * - User.roles 多对多关联的表 userrole 外键为 ondelete="CASCADE"，
 * 删除用户时数据库会自动清理其与角色的关联。
 */
export const deleteUserV1UsersUserIdDeleteMutation = (options?: Partial<Options<DeleteUserV1UsersUserIdDeleteData>>): UseMutationOptions<DeleteUserV1UsersUserIdDeleteResponse, DeleteUserV1UsersUserIdDeleteError, Options<DeleteUserV1UsersUserIdDeleteData>> => {
    const mutationOptions: UseMutationOptions<DeleteUserV1UsersUserIdDeleteResponse, DeleteUserV1UsersUserIdDeleteError, Options<DeleteUserV1UsersUserIdDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteUserV1UsersUserIdDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const readUserByIdV1UsersUserIdGetQueryKey = (options: Options<ReadUserByIdV1UsersUserIdGetData>) => createQueryKey('readUserByIdV1UsersUserIdGet', options);

/**
 * Read User By Id
 *
 * 获取指定用户信息。
 *
 * 权限：拥有 user:read scope。
 *
 * 参数：
 * - user_id：目标用户 UUID
 * - session：数据库会话
 * - current_user：当前登录用户
 *
 * 返回值：
 * - UserPublic：用户信息
 *
 * 业务流程：
 * 1. 查询指定用户
 * 2. 若不存在，返回 404
 *
 * 异常：
 * - 403：无 user:read scope
 * - 404：用户不存在
 */
export const readUserByIdV1UsersUserIdGetOptions = (options: Options<ReadUserByIdV1UsersUserIdGetData>) => queryOptions<ReadUserByIdV1UsersUserIdGetResponse, ReadUserByIdV1UsersUserIdGetError, ReadUserByIdV1UsersUserIdGetResponse, ReturnType<typeof readUserByIdV1UsersUserIdGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readUserByIdV1UsersUserIdGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readUserByIdV1UsersUserIdGetQueryKey(options)
});

/**
 * Update User
 *
 * 更新指定用户信息（scope 判定）。
 *
 * 权限：拥有 user:update scope。
 *
 * 参数：
 * - session：数据库会话
 * - user_id：目标用户 UUID
 * - user_in：用户更新 DTO（email、password、is_active、is_superuser 等可选）
 *
 * 返回值：
 * - UserPublic：更新后的用户信息
 *
 * 业务流程：
 * 1. 查询目标用户是否存在
 * 2. 若修改邮箱，检查新邮箱唯一性（允许保持原邮箱）
 * 3. 调用 repository.update_user() 更新用户
 * 4. 返回更新后的用户
 *
 * 异常：
 * - 404：用户不存在
 * - 409：新邮箱被其他用户占用
 * - 403：无 user:update scope
 */
export const updateUserV1UsersUserIdPatchMutation = (options?: Partial<Options<UpdateUserV1UsersUserIdPatchData>>): UseMutationOptions<UpdateUserV1UsersUserIdPatchResponse, UpdateUserV1UsersUserIdPatchError, Options<UpdateUserV1UsersUserIdPatchData>> => {
    const mutationOptions: UseMutationOptions<UpdateUserV1UsersUserIdPatchResponse, UpdateUserV1UsersUserIdPatchError, Options<UpdateUserV1UsersUserIdPatchData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateUserV1UsersUserIdPatch({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const readRolesV1RolesGetQueryKey = (options?: Options<ReadRolesV1RolesGetData>) => createQueryKey('readRolesV1RolesGet', options);

/**
 * Read Roles
 *
 * 获取角色列表（分页）。
 *
 * 权限：拥有 role:read scope。
 *
 * 返回：
 * - RolesPublic：data（角色列表，含 scopes）、count、page、page_size、total_pages
 */
export const readRolesV1RolesGetOptions = (options?: Options<ReadRolesV1RolesGetData>) => queryOptions<ReadRolesV1RolesGetResponse, ReadRolesV1RolesGetError, ReadRolesV1RolesGetResponse, ReturnType<typeof readRolesV1RolesGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readRolesV1RolesGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readRolesV1RolesGetQueryKey(options)
});

export const readRolesV1RolesGetInfiniteQueryKey = (options?: Options<ReadRolesV1RolesGetData>): QueryKey<Options<ReadRolesV1RolesGetData>> => createQueryKey('readRolesV1RolesGet', options, true);

/**
 * Read Roles
 *
 * 获取角色列表（分页）。
 *
 * 权限：拥有 role:read scope。
 *
 * 返回：
 * - RolesPublic：data（角色列表，含 scopes）、count、page、page_size、total_pages
 */
export const readRolesV1RolesGetInfiniteOptions = (options?: Options<ReadRolesV1RolesGetData>) => infiniteQueryOptions<ReadRolesV1RolesGetResponse, ReadRolesV1RolesGetError, InfiniteData<ReadRolesV1RolesGetResponse>, QueryKey<Options<ReadRolesV1RolesGetData>>, number | Pick<QueryKey<Options<ReadRolesV1RolesGetData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ReadRolesV1RolesGetData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await readRolesV1RolesGet({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readRolesV1RolesGetInfiniteQueryKey(options)
});

/**
 * Create Role
 *
 * 创建新角色。
 *
 * 权限：拥有 role:create scope。
 *
 * 参数：
 * - role_in：RoleCreate（name 必填，scopes 可选）
 *
 * 异常：
 * - 409：角色名已存在
 * - 400：包含未定义的 scope
 */
export const createRoleV1RolesPostMutation = (options?: Partial<Options<CreateRoleV1RolesPostData>>): UseMutationOptions<CreateRoleV1RolesPostResponse, CreateRoleV1RolesPostError, Options<CreateRoleV1RolesPostData>> => {
    const mutationOptions: UseMutationOptions<CreateRoleV1RolesPostResponse, CreateRoleV1RolesPostError, Options<CreateRoleV1RolesPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createRoleV1RolesPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Role
 *
 * 删除角色。
 *
 * 权限：拥有 role:delete scope。
 *
 * 注意：
 * - 系统预置角色（viewer / editor / admin）不允许删除。
 * - 角色删除后，引用它的用户会自动解除关联（UserRole 外键 CASCADE）。
 *
 * 异常：
 * - 404：角色不存在
 * - 400：删除预置角色
 */
export const deleteRoleV1RolesRoleIdDeleteMutation = (options?: Partial<Options<DeleteRoleV1RolesRoleIdDeleteData>>): UseMutationOptions<DeleteRoleV1RolesRoleIdDeleteResponse, DeleteRoleV1RolesRoleIdDeleteError, Options<DeleteRoleV1RolesRoleIdDeleteData>> => {
    const mutationOptions: UseMutationOptions<DeleteRoleV1RolesRoleIdDeleteResponse, DeleteRoleV1RolesRoleIdDeleteError, Options<DeleteRoleV1RolesRoleIdDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteRoleV1RolesRoleIdDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const readRoleV1RolesRoleIdGetQueryKey = (options: Options<ReadRoleV1RolesRoleIdGetData>) => createQueryKey('readRoleV1RolesRoleIdGet', options);

/**
 * Read Role
 *
 * 获取单个角色详情（含 scopes 列表）。
 *
 * 权限：拥有 role:read scope。
 */
export const readRoleV1RolesRoleIdGetOptions = (options: Options<ReadRoleV1RolesRoleIdGetData>) => queryOptions<ReadRoleV1RolesRoleIdGetResponse, ReadRoleV1RolesRoleIdGetError, ReadRoleV1RolesRoleIdGetResponse, ReturnType<typeof readRoleV1RolesRoleIdGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readRoleV1RolesRoleIdGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readRoleV1RolesRoleIdGetQueryKey(options)
});

/**
 * Update Role
 *
 * 更新角色（修改名字和/或它的 scope 集合）。
 *
 * 权限：拥有 role:update scope。
 *
 * 参数：
 * - role_id：目标角色 UUID
 * - role_in：RoleUpdate（name、scopes 均可选）
 *
 * 业务规则：
 * - 传入 scopes 时整体替换（先删后插），实现增减权限的效果。
 * - 系统预置角色（viewer / editor / admin）不允许修改。
 *
 * 异常：
 * - 404：角色不存在
 * - 400：角色名与其他角色冲突 / 包含未定义 scope / 修改预置角色
 */
export const updateRoleV1RolesRoleIdPatchMutation = (options?: Partial<Options<UpdateRoleV1RolesRoleIdPatchData>>): UseMutationOptions<UpdateRoleV1RolesRoleIdPatchResponse, UpdateRoleV1RolesRoleIdPatchError, Options<UpdateRoleV1RolesRoleIdPatchData>> => {
    const mutationOptions: UseMutationOptions<UpdateRoleV1RolesRoleIdPatchResponse, UpdateRoleV1RolesRoleIdPatchError, Options<UpdateRoleV1RolesRoleIdPatchData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateRoleV1RolesRoleIdPatch({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
