// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen.js';
import { createItemV1ItemsPost, createUserV1UsersPost, deleteItemV1ItemsIdDelete, deleteUserMeV1UsersMeDelete, deleteUserV1UsersUserIdDelete, healthCheckV1UsersHealthCheckGet, loginAccessTokenV1LoginAccessTokenPost, type Options, readItemsV1ItemsGet, readItemV1ItemsIdGet, readUserByIdV1UsersUserIdGet, readUserMeV1UsersMeGet, readUsersV1UsersGet, registerUserV1UsersSignupPost, resetPasswordV1ResetPasswordPost, testTokenV1LoginTestTokenPost, updateItemV1ItemsIdPut, updatePasswordMeV1UsersMePasswordPatch, updateUserMeV1UsersMePatch, updateUserV1UsersUserIdPatch } from '../sdk.gen.js';
import type { CreateItemV1ItemsPostData, CreateItemV1ItemsPostError, CreateItemV1ItemsPostResponse, CreateUserV1UsersPostData, CreateUserV1UsersPostError, CreateUserV1UsersPostResponse, DeleteItemV1ItemsIdDeleteData, DeleteItemV1ItemsIdDeleteError, DeleteItemV1ItemsIdDeleteResponse, DeleteUserMeV1UsersMeDeleteData, DeleteUserMeV1UsersMeDeleteResponse, DeleteUserV1UsersUserIdDeleteData, DeleteUserV1UsersUserIdDeleteError, DeleteUserV1UsersUserIdDeleteResponse, HealthCheckV1UsersHealthCheckGetData, HealthCheckV1UsersHealthCheckGetResponse, LoginAccessTokenV1LoginAccessTokenPostData, LoginAccessTokenV1LoginAccessTokenPostError, LoginAccessTokenV1LoginAccessTokenPostResponse, ReadItemsV1ItemsGetData, ReadItemsV1ItemsGetError, ReadItemsV1ItemsGetResponse, ReadItemV1ItemsIdGetData, ReadItemV1ItemsIdGetError, ReadItemV1ItemsIdGetResponse, ReadUserByIdV1UsersUserIdGetData, ReadUserByIdV1UsersUserIdGetError, ReadUserByIdV1UsersUserIdGetResponse, ReadUserMeV1UsersMeGetData, ReadUserMeV1UsersMeGetResponse, ReadUsersV1UsersGetData, ReadUsersV1UsersGetError, ReadUsersV1UsersGetResponse, RegisterUserV1UsersSignupPostData, RegisterUserV1UsersSignupPostError, RegisterUserV1UsersSignupPostResponse, ResetPasswordV1ResetPasswordPostData, ResetPasswordV1ResetPasswordPostError, ResetPasswordV1ResetPasswordPostResponse, TestTokenV1LoginTestTokenPostData, TestTokenV1LoginTestTokenPostResponse, UpdateItemV1ItemsIdPutData, UpdateItemV1ItemsIdPutError, UpdateItemV1ItemsIdPutResponse, UpdatePasswordMeV1UsersMePasswordPatchData, UpdatePasswordMeV1UsersMePasswordPatchError, UpdatePasswordMeV1UsersMePasswordPatchResponse, UpdateUserMeV1UsersMePatchData, UpdateUserMeV1UsersMePatchError, UpdateUserMeV1UsersMePatchResponse, UpdateUserV1UsersUserIdPatchData, UpdateUserV1UsersUserIdPatchError, UpdateUserV1UsersUserIdPatchResponse } from '../types.gen.js';

/**
 * Login Access Token
 *
 * OAuth2 compatible token login, get an access token for future requests
 */
export const loginAccessTokenV1LoginAccessTokenPostMutation = (options?: Partial<Options<LoginAccessTokenV1LoginAccessTokenPostData>>): UseMutationOptions<LoginAccessTokenV1LoginAccessTokenPostResponse, LoginAccessTokenV1LoginAccessTokenPostError, Options<LoginAccessTokenV1LoginAccessTokenPostData>> => {
    const mutationOptions: UseMutationOptions<LoginAccessTokenV1LoginAccessTokenPostResponse, LoginAccessTokenV1LoginAccessTokenPostError, Options<LoginAccessTokenV1LoginAccessTokenPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await loginAccessTokenV1LoginAccessTokenPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Test Token
 *
 * Test access token
 */
export const testTokenV1LoginTestTokenPostMutation = (options?: Partial<Options<TestTokenV1LoginTestTokenPostData>>): UseMutationOptions<TestTokenV1LoginTestTokenPostResponse, DefaultError, Options<TestTokenV1LoginTestTokenPostData>> => {
    const mutationOptions: UseMutationOptions<TestTokenV1LoginTestTokenPostResponse, DefaultError, Options<TestTokenV1LoginTestTokenPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await testTokenV1LoginTestTokenPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Reset Password
 *
 * Reset password
 */
export const resetPasswordV1ResetPasswordPostMutation = (options?: Partial<Options<ResetPasswordV1ResetPasswordPostData>>): UseMutationOptions<ResetPasswordV1ResetPasswordPostResponse, ResetPasswordV1ResetPasswordPostError, Options<ResetPasswordV1ResetPasswordPostData>> => {
    const mutationOptions: UseMutationOptions<ResetPasswordV1ResetPasswordPostResponse, ResetPasswordV1ResetPasswordPostError, Options<ResetPasswordV1ResetPasswordPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await resetPasswordV1ResetPasswordPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const readUsersV1UsersGetQueryKey = (options?: Options<ReadUsersV1UsersGetData>) => createQueryKey('readUsersV1UsersGet', options);

/**
 * Read Users
 *
 * 获取所有用户列表（分页）。
 *
 * 权限：超管-only（通过 dependencies 依赖注入强制）
 *
 * 参数：
 * - session：数据库会话（依赖注入）
 * - pagination：分页参数（page, page_size）
 *
 * 返回值：
 * - UsersPublic：包含 data（用户列表）、count（总数）、page（当前页）、page_size（每页大小）、total_pages（总页数）
 *
 * 查询语句：
 * 1. 使用 func.count() 获取用户总数
 * 2. 使用 order_by(col(User.created_at).desc()) 按创建时间降序排列
 * 3. 使用 offset/limit 分页
 */
export const readUsersV1UsersGetOptions = (options?: Options<ReadUsersV1UsersGetData>) => queryOptions<ReadUsersV1UsersGetResponse, ReadUsersV1UsersGetError, ReadUsersV1UsersGetResponse, ReturnType<typeof readUsersV1UsersGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readUsersV1UsersGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readUsersV1UsersGetQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const readUsersV1UsersGetInfiniteQueryKey = (options?: Options<ReadUsersV1UsersGetData>): QueryKey<Options<ReadUsersV1UsersGetData>> => createQueryKey('readUsersV1UsersGet', options, true);

/**
 * Read Users
 *
 * 获取所有用户列表（分页）。
 *
 * 权限：超管-only（通过 dependencies 依赖注入强制）
 *
 * 参数：
 * - session：数据库会话（依赖注入）
 * - pagination：分页参数（page, page_size）
 *
 * 返回值：
 * - UsersPublic：包含 data（用户列表）、count（总数）、page（当前页）、page_size（每页大小）、total_pages（总页数）
 *
 * 查询语句：
 * 1. 使用 func.count() 获取用户总数
 * 2. 使用 order_by(col(User.created_at).desc()) 按创建时间降序排列
 * 3. 使用 offset/limit 分页
 */
export const readUsersV1UsersGetInfiniteOptions = (options?: Options<ReadUsersV1UsersGetData>) => infiniteQueryOptions<ReadUsersV1UsersGetResponse, ReadUsersV1UsersGetError, InfiniteData<ReadUsersV1UsersGetResponse>, QueryKey<Options<ReadUsersV1UsersGetData>>, number | Pick<QueryKey<Options<ReadUsersV1UsersGetData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ReadUsersV1UsersGetData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await readUsersV1UsersGet({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readUsersV1UsersGetInfiniteQueryKey(options)
});

/**
 * Create User
 *
 * 创建新用户（超管操作）。
 *
 * 权限：超管-only
 *
 * 参数：
 * - session：数据库会话
 * - user_in：用户创建 DTO（包含邮箱、密码等）
 *
 * 返回值：
 * - UserPublic：创建成功的用户信息
 *
 * 业务流程：
 * 1. 检查邮箱是否已存在，存在则返回 400 错误
 * 2. 调用 repository create_user() 创建用户（密码自动哈希）
 * 3. 若启用邮件服务，生成新账户邮件并发送
 *
 * 邮件通知：
 * - 包含临时密码（用于提醒用户首次修改）
 * - 若邮件发送失败不影响用户创建成功
 */
export const createUserV1UsersPostMutation = (options?: Partial<Options<CreateUserV1UsersPostData>>): UseMutationOptions<CreateUserV1UsersPostResponse, CreateUserV1UsersPostError, Options<CreateUserV1UsersPostData>> => {
    const mutationOptions: UseMutationOptions<CreateUserV1UsersPostResponse, CreateUserV1UsersPostError, Options<CreateUserV1UsersPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createUserV1UsersPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete User Me
 *
 * 删除当前用户自己的账户。
 *
 * 权限：登录用户
 *
 * 参数：
 * - session：数据库会话
 * - current_user：当前登录用户
 *
 * 返回值：
 * - Message：删除成功消息
 *
 * 业务逻辑：
 * 1. 检查当前用户是否为超管，超管不允许自删除（防止误操作导致系统无超管）
 * 2. 删除用户记录
 * 3. 级联删除会由数据库约束自动处理（User.items 有 cascade_delete=True）
 *
 * 异常：
 * - 403：超管不允许删除自己
 */
export const deleteUserMeV1UsersMeDeleteMutation = (options?: Partial<Options<DeleteUserMeV1UsersMeDeleteData>>): UseMutationOptions<DeleteUserMeV1UsersMeDeleteResponse, DefaultError, Options<DeleteUserMeV1UsersMeDeleteData>> => {
    const mutationOptions: UseMutationOptions<DeleteUserMeV1UsersMeDeleteResponse, DefaultError, Options<DeleteUserMeV1UsersMeDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteUserMeV1UsersMeDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const readUserMeV1UsersMeGetQueryKey = (options?: Options<ReadUserMeV1UsersMeGetData>) => createQueryKey('readUserMeV1UsersMeGet', options);

/**
 * Read User Me
 *
 * 获取当前登录用户的信息。
 *
 * 权限：登录用户
 *
 * 参数：
 * - current_user：当前登录用户（依赖注入）
 *
 * 返回值：
 * - UserPublic：当前用户信息
 *
 * 说明：
 * - 无需数据库查询，直接返回依赖注入的 current_user
 * - 用于前端检查登录状态、显示用户信息
 */
export const readUserMeV1UsersMeGetOptions = (options?: Options<ReadUserMeV1UsersMeGetData>) => queryOptions<ReadUserMeV1UsersMeGetResponse, DefaultError, ReadUserMeV1UsersMeGetResponse, ReturnType<typeof readUserMeV1UsersMeGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readUserMeV1UsersMeGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readUserMeV1UsersMeGetQueryKey(options)
});

/**
 * Update User Me
 *
 * 更新当前用户自己的信息。
 *
 * 权限：登录用户（自己的账户）
 *
 * 参数：
 * - session：数据库会话
 * - user_in：用户更新 DTO（full_name、email 可选）
 * - current_user：当前登录用户（依赖注入）
 *
 * 返回值：
 * - UserPublic：更新后的用户信息
 *
 * 业务逻辑：
 * 1. 若修改邮箱，检查新邮箱是否被其他用户占用
 * 2. 使用 model_dump(exclude_unset=True) 仅获取用户明确设置的字段
 * 3. 使用 sqlmodel_update() 合并更新
 * 4. 提交事务
 *
 * 邮箱冲突处理：
 * - 允许用户更新为自己的原邮箱
 * - 若邮箱被其他用户占用，返回 409 冲突错误
 */
export const updateUserMeV1UsersMePatchMutation = (options?: Partial<Options<UpdateUserMeV1UsersMePatchData>>): UseMutationOptions<UpdateUserMeV1UsersMePatchResponse, UpdateUserMeV1UsersMePatchError, Options<UpdateUserMeV1UsersMePatchData>> => {
    const mutationOptions: UseMutationOptions<UpdateUserMeV1UsersMePatchResponse, UpdateUserMeV1UsersMePatchError, Options<UpdateUserMeV1UsersMePatchData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateUserMeV1UsersMePatch({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update Password Me
 *
 * 修改当前用户自己的密码。
 *
 * 权限：登录用户
 *
 * 参数：
 * - session：数据库会话
 * - body：密码更新 DTO（current_password、new_password）
 * - current_user：当前登录用户
 *
 * 返回值：
 * - Message：成功消息
 *
 * 业务流程：
 * 1. 验证现有密码是否正确（调用 verify_password）
 * 2. 检查新密码是否与旧密码相同（防止无意义操作）
 * 3. 哈希新密码并保存到数据库
 * 4. 返回成功消息
 *
 * 验证失败返回：
 * - 400：密码错误
 * - 400：新密码与旧密码相同
 */
export const updatePasswordMeV1UsersMePasswordPatchMutation = (options?: Partial<Options<UpdatePasswordMeV1UsersMePasswordPatchData>>): UseMutationOptions<UpdatePasswordMeV1UsersMePasswordPatchResponse, UpdatePasswordMeV1UsersMePasswordPatchError, Options<UpdatePasswordMeV1UsersMePasswordPatchData>> => {
    const mutationOptions: UseMutationOptions<UpdatePasswordMeV1UsersMePasswordPatchResponse, UpdatePasswordMeV1UsersMePasswordPatchError, Options<UpdatePasswordMeV1UsersMePasswordPatchData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updatePasswordMeV1UsersMePasswordPatch({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Register User
 *
 * 用户自助注册（无需登录）。
 *
 * 权限：公开
 *
 * 参数：
 * - session：数据库会话
 * - user_in：用户注册 DTO（邮箱、密码、姓名）
 *
 * 返回值：
 * - UserPublic：创建的用户信息
 *
 * 业务流程：
 * 1. 检查邮箱是否已存在
 * 2. 使用 model_validate 将 UserRegister DTO 转换为 UserCreate DTO
 * 3. 调用 repository.create_user() 创建用户
 *
 * 异常：
 * - 400：邮箱已被注册
 *
 * 与 /users POST 的区别：
 * - 此路由无需超管权限，任何人可注册
 * - 此路由不发送邮件通知
 */
export const registerUserV1UsersSignupPostMutation = (options?: Partial<Options<RegisterUserV1UsersSignupPostData>>): UseMutationOptions<RegisterUserV1UsersSignupPostResponse, RegisterUserV1UsersSignupPostError, Options<RegisterUserV1UsersSignupPostData>> => {
    const mutationOptions: UseMutationOptions<RegisterUserV1UsersSignupPostResponse, RegisterUserV1UsersSignupPostError, Options<RegisterUserV1UsersSignupPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await registerUserV1UsersSignupPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete User
 *
 * 删除指定用户（超管操作）。
 *
 * 权限：超管-only
 *
 * 参数：
 * - session：数据库会话
 * - current_user：当前超管用户（用于权限检查）
 * - user_id：目标用户 UUID
 *
 * 返回值：
 * - Message：删除成功消息
 *
 * 业务流程：
 * 1. 查询目标用户是否存在
 * 2. 防止超管删除自己（防止系统无超管）
 * 3. 手动删除该用户的所有 Item（因为关联表可能有特殊处理）
 * 4. 删除用户记录（级联会自动删除 items）
 * 5. 提交事务
 *
 * 异常：
 * - 404：用户不存在
 * - 403：不允许删除自己
 *
 * 注意：
 * - 虽然 User.items 有 cascade_delete=True，但此处显式删除 Item
 * - 这是为了确保数据库一致性和日志记录，避免某些场景下级联失败
 */
export const deleteUserV1UsersUserIdDeleteMutation = (options?: Partial<Options<DeleteUserV1UsersUserIdDeleteData>>): UseMutationOptions<DeleteUserV1UsersUserIdDeleteResponse, DeleteUserV1UsersUserIdDeleteError, Options<DeleteUserV1UsersUserIdDeleteData>> => {
    const mutationOptions: UseMutationOptions<DeleteUserV1UsersUserIdDeleteResponse, DeleteUserV1UsersUserIdDeleteError, Options<DeleteUserV1UsersUserIdDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteUserV1UsersUserIdDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const readUserByIdV1UsersUserIdGetQueryKey = (options: Options<ReadUserByIdV1UsersUserIdGetData>) => createQueryKey('readUserByIdV1UsersUserIdGet', options);

/**
 * Read User By Id
 *
 * 获取指定用户信息。
 *
 * 权限：
 * - 用户可查看自己的信息
 * - 超管可查看任何用户信息
 *
 * 参数：
 * - user_id：目标用户 UUID
 * - session：数据库会话
 * - current_user：当前登录用户
 *
 * 返回值：
 * - UserPublic：用户信息
 *
 * 业务流程：
 * 1. 查询指定用户
 * 2. 若为自己，直接返回
 * 3. 若不是自己且当前用户非超管，返回 403 禁止访问
 * 4. 若用户不存在，返回 404
 *
 * 异常：
 * - 403：权限不足
 * - 404：用户不存在
 */
export const readUserByIdV1UsersUserIdGetOptions = (options: Options<ReadUserByIdV1UsersUserIdGetData>) => queryOptions<ReadUserByIdV1UsersUserIdGetResponse, ReadUserByIdV1UsersUserIdGetError, ReadUserByIdV1UsersUserIdGetResponse, ReturnType<typeof readUserByIdV1UsersUserIdGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readUserByIdV1UsersUserIdGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readUserByIdV1UsersUserIdGetQueryKey(options)
});

/**
 * Update User
 *
 * 更新指定用户信息（超管操作）。
 *
 * 权限：超管-only
 *
 * 参数：
 * - session：数据库会话
 * - user_id：目标用户 UUID
 * - user_in：用户更新 DTO（email、password、is_active、is_superuser 等可选）
 *
 * 返回值：
 * - UserPublic：更新后的用户信息
 *
 * 业务流程：
 * 1. 查询目标用户是否存在
 * 2. 若修改邮箱，检查新邮箱唯一性（允许保持原邮箱）
 * 3. 调用 repository.update_user() 更新用户
 * 4. 返回更新后的用户
 *
 * 异常：
 * - 404：用户不存在
 * - 409：新邮箱被其他用户占用
 */
export const updateUserV1UsersUserIdPatchMutation = (options?: Partial<Options<UpdateUserV1UsersUserIdPatchData>>): UseMutationOptions<UpdateUserV1UsersUserIdPatchResponse, UpdateUserV1UsersUserIdPatchError, Options<UpdateUserV1UsersUserIdPatchData>> => {
    const mutationOptions: UseMutationOptions<UpdateUserV1UsersUserIdPatchResponse, UpdateUserV1UsersUserIdPatchError, Options<UpdateUserV1UsersUserIdPatchData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateUserV1UsersUserIdPatch({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const healthCheckV1UsersHealthCheckGetQueryKey = (options?: Options<HealthCheckV1UsersHealthCheckGetData>) => createQueryKey('healthCheckV1UsersHealthCheckGet', options);

/**
 * Health Check
 */
export const healthCheckV1UsersHealthCheckGetOptions = (options?: Options<HealthCheckV1UsersHealthCheckGetData>) => queryOptions<HealthCheckV1UsersHealthCheckGetResponse, DefaultError, HealthCheckV1UsersHealthCheckGetResponse, ReturnType<typeof healthCheckV1UsersHealthCheckGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await healthCheckV1UsersHealthCheckGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthCheckV1UsersHealthCheckGetQueryKey(options)
});

export const readItemsV1ItemsGetQueryKey = (options?: Options<ReadItemsV1ItemsGetData>) => createQueryKey('readItemsV1ItemsGet', options);

/**
 * Read Items
 *
 * Retrieve items.
 *
 * - 普通用户只能查看自己的 items
 * - 拥有 item:admin 权限的用户可以查看所有 items
 */
export const readItemsV1ItemsGetOptions = (options?: Options<ReadItemsV1ItemsGetData>) => queryOptions<ReadItemsV1ItemsGetResponse, ReadItemsV1ItemsGetError, ReadItemsV1ItemsGetResponse, ReturnType<typeof readItemsV1ItemsGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readItemsV1ItemsGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readItemsV1ItemsGetQueryKey(options)
});

export const readItemsV1ItemsGetInfiniteQueryKey = (options?: Options<ReadItemsV1ItemsGetData>): QueryKey<Options<ReadItemsV1ItemsGetData>> => createQueryKey('readItemsV1ItemsGet', options, true);

/**
 * Read Items
 *
 * Retrieve items.
 *
 * - 普通用户只能查看自己的 items
 * - 拥有 item:admin 权限的用户可以查看所有 items
 */
export const readItemsV1ItemsGetInfiniteOptions = (options?: Options<ReadItemsV1ItemsGetData>) => infiniteQueryOptions<ReadItemsV1ItemsGetResponse, ReadItemsV1ItemsGetError, InfiniteData<ReadItemsV1ItemsGetResponse>, QueryKey<Options<ReadItemsV1ItemsGetData>>, number | Pick<QueryKey<Options<ReadItemsV1ItemsGetData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ReadItemsV1ItemsGetData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await readItemsV1ItemsGet({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readItemsV1ItemsGetInfiniteQueryKey(options)
});

/**
 * Create Item
 *
 * Create new item.
 *
 * 需要 item:create 权限。
 */
export const createItemV1ItemsPostMutation = (options?: Partial<Options<CreateItemV1ItemsPostData>>): UseMutationOptions<CreateItemV1ItemsPostResponse, CreateItemV1ItemsPostError, Options<CreateItemV1ItemsPostData>> => {
    const mutationOptions: UseMutationOptions<CreateItemV1ItemsPostResponse, CreateItemV1ItemsPostError, Options<CreateItemV1ItemsPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createItemV1ItemsPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Item
 *
 * Delete an item.
 *
 * - 普通用户只能删除自己的 item（需要 item:delete 权限）
 * - 拥有 item:admin 权限的用户可以删除任何 item
 */
export const deleteItemV1ItemsIdDeleteMutation = (options?: Partial<Options<DeleteItemV1ItemsIdDeleteData>>): UseMutationOptions<DeleteItemV1ItemsIdDeleteResponse, DeleteItemV1ItemsIdDeleteError, Options<DeleteItemV1ItemsIdDeleteData>> => {
    const mutationOptions: UseMutationOptions<DeleteItemV1ItemsIdDeleteResponse, DeleteItemV1ItemsIdDeleteError, Options<DeleteItemV1ItemsIdDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteItemV1ItemsIdDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const readItemV1ItemsIdGetQueryKey = (options: Options<ReadItemV1ItemsIdGetData>) => createQueryKey('readItemV1ItemsIdGet', options);

/**
 * Read Item
 *
 * Get item by ID.
 *
 * - 普通用户只能查看自己的 item
 * - 拥有 item:admin 权限的用户可以查看任何 item
 */
export const readItemV1ItemsIdGetOptions = (options: Options<ReadItemV1ItemsIdGetData>) => queryOptions<ReadItemV1ItemsIdGetResponse, ReadItemV1ItemsIdGetError, ReadItemV1ItemsIdGetResponse, ReturnType<typeof readItemV1ItemsIdGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readItemV1ItemsIdGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readItemV1ItemsIdGetQueryKey(options)
});

/**
 * Update Item
 *
 * Update an item.
 *
 * - 普通用户只能更新自己的 item（需要 item:update 权限）
 * - 拥有 item:admin 权限的用户可以更新任何 item
 */
export const updateItemV1ItemsIdPutMutation = (options?: Partial<Options<UpdateItemV1ItemsIdPutData>>): UseMutationOptions<UpdateItemV1ItemsIdPutResponse, UpdateItemV1ItemsIdPutError, Options<UpdateItemV1ItemsIdPutData>> => {
    const mutationOptions: UseMutationOptions<UpdateItemV1ItemsIdPutResponse, UpdateItemV1ItemsIdPutError, Options<UpdateItemV1ItemsIdPutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateItemV1ItemsIdPut({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
