// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import { type Client, type Options as Options2, type TDataShape, urlSearchParamsBodySerializer } from './client/index.js';
import type { CreateRoleV1RolesPostData, CreateRoleV1RolesPostErrors, CreateRoleV1RolesPostResponses, CreateUserV1UsersPostData, CreateUserV1UsersPostErrors, CreateUserV1UsersPostResponses, DeleteRoleV1RolesRoleIdDeleteData, DeleteRoleV1RolesRoleIdDeleteErrors, DeleteRoleV1RolesRoleIdDeleteResponses, DeleteUserMeV1UsersMeDeleteData, DeleteUserMeV1UsersMeDeleteResponses, DeleteUserV1UsersUserIdDeleteData, DeleteUserV1UsersUserIdDeleteErrors, DeleteUserV1UsersUserIdDeleteResponses, HealthCheckV1HealthCheckGetData, HealthCheckV1HealthCheckGetResponses, LoginAccessTokenV1LoginAccessTokenPostData, LoginAccessTokenV1LoginAccessTokenPostErrors, LoginAccessTokenV1LoginAccessTokenPostResponses, ReadRolesV1RolesGetData, ReadRolesV1RolesGetErrors, ReadRolesV1RolesGetResponses, ReadRoleV1RolesRoleIdGetData, ReadRoleV1RolesRoleIdGetErrors, ReadRoleV1RolesRoleIdGetResponses, ReadUserByIdV1UsersUserIdGetData, ReadUserByIdV1UsersUserIdGetErrors, ReadUserByIdV1UsersUserIdGetResponses, ReadUserMeV1UsersMeGetData, ReadUserMeV1UsersMeGetResponses, ReadUsersV1UsersGetData, ReadUsersV1UsersGetErrors, ReadUsersV1UsersGetResponses, RegisterUserV1UsersSignupPostData, RegisterUserV1UsersSignupPostErrors, RegisterUserV1UsersSignupPostResponses, TestTokenV1LoginTestTokenPostData, TestTokenV1LoginTestTokenPostResponses, UpdatePasswordMeV1UsersMePasswordPatchData, UpdatePasswordMeV1UsersMePasswordPatchErrors, UpdatePasswordMeV1UsersMePasswordPatchResponses, UpdateRoleV1RolesRoleIdPatchData, UpdateRoleV1RolesRoleIdPatchErrors, UpdateRoleV1RolesRoleIdPatchResponses, UpdateUserMeV1UsersMePatchData, UpdateUserMeV1UsersMePatchErrors, UpdateUserMeV1UsersMePatchResponses, UpdateUserV1UsersUserIdPatchData, UpdateUserV1UsersUserIdPatchErrors, UpdateUserV1UsersUserIdPatchResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health Check
 *
 * 健康检查端点，返回 True 表示服务正常运行。
 */
export const healthCheckV1HealthCheckGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckV1HealthCheckGetData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckV1HealthCheckGetResponses, unknown, ThrowOnError>({ url: '/v1/health-check', ...options });

/**
 * Login Access Token
 *
 * OAuth2 兼容的令牌登录：验证邮箱密码，签发访问令牌。
 *
 * 参数：
 * - session：数据库会话
 * - form_data：OAuth2 表单（username=邮箱，password=密码）
 *
 * 返回值：
 * - Token：访问令牌（JWT）
 *
 * 异常：
 * - 400：邮箱或密码错误 / 用户未激活
 */
export const loginAccessTokenV1LoginAccessTokenPost = <ThrowOnError extends boolean = false>(options: Options<LoginAccessTokenV1LoginAccessTokenPostData, ThrowOnError>) => (options.client ?? client).post<LoginAccessTokenV1LoginAccessTokenPostResponses, LoginAccessTokenV1LoginAccessTokenPostErrors, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    url: '/v1/login/access-token',
    ...options,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options.headers
    }
});

/**
 * Test Token
 *
 * 校验访问令牌并返回当前用户信息（含权限 scope 列表）。
 *
 * 参数：
 * - session：数据库会话
 * - current_user：当前登录用户（依赖注入）
 *
 * 返回值：
 * - UserPublic：当前用户信息（含 scopes）
 */
export const testTokenV1LoginTestTokenPost = <ThrowOnError extends boolean = false>(options?: Options<TestTokenV1LoginTestTokenPostData, ThrowOnError>) => (options?.client ?? client).post<TestTokenV1LoginTestTokenPostResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/login/test-token',
    ...options
});

/**
 * Read Users
 *
 * 获取所有用户列表（分页）。
 *
 * 权限：拥有 user:read scope（通过 dependencies 依赖注入强制）。
 *
 * 参数：
 * - session：数据库会话（依赖注入）
 * - pagination：分页参数（page, page_size）
 *
 * 返回值：
 * - UsersPublic：包含 data（用户列表）、count（总数）、page（当前页）、page_size（每页大小）、total_pages（总页数）
 */
export const readUsersV1UsersGet = <ThrowOnError extends boolean = false>(options?: Options<ReadUsersV1UsersGetData, ThrowOnError>) => (options?.client ?? client).get<ReadUsersV1UsersGetResponses, ReadUsersV1UsersGetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/users/',
    ...options
});

/**
 * Create User
 *
 * 创建新用户。
 *
 * 权限：拥有 user:create scope。
 *
 * 参数：
 * - session：数据库会话
 * - user_in：用户创建 DTO（包含邮箱、密码等）
 *
 * 返回值：
 * - UserPublic：创建成功的用户信息
 *
 * 业务流程：
 * 1. 检查邮箱是否已存在，存在则返回 409 错误
 * 2. 调用 repository create_user() 创建用户（密码自动哈希，默认分配 viewer 角色）
 */
export const createUserV1UsersPost = <ThrowOnError extends boolean = false>(options: Options<CreateUserV1UsersPostData, ThrowOnError>) => (options.client ?? client).post<CreateUserV1UsersPostResponses, CreateUserV1UsersPostErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/users/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete User Me
 *
 * 删除当前用户自己的账户。
 *
 * 权限：登录用户
 *
 * 参数：
 * - session：数据库会话
 * - current_user：当前登录用户
 *
 * 返回值：
 * - Message：删除成功消息
 *
 * 业务逻辑：
 * 1. 检查当前用户是否为超管，超管不允许自删除（防止误操作导致系统无超管）
 * 2. 使用仓库函数删除用户记录
 * 3. 级联删除会由数据库约束自动处理（User.roles 关联表 userrole 外键为 CASCADE）
 *
 * 异常：
 * - 403：超管不允许删除自己
 */
export const deleteUserMeV1UsersMeDelete = <ThrowOnError extends boolean = false>(options?: Options<DeleteUserMeV1UsersMeDeleteData, ThrowOnError>) => (options?.client ?? client).delete<DeleteUserMeV1UsersMeDeleteResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/users/me',
    ...options
});

/**
 * Read User Me
 *
 * 获取当前登录用户的信息。
 *
 * 权限：登录用户
 *
 * 参数：
 * - session：数据库会话（用于计算权限 scope）
 * - current_user：当前登录用户（依赖注入）
 *
 * 返回值：
 * - UserPublic：当前用户信息（含 scopes 权限列表）
 *
 * 说明：
 * - scopes 由 get_user_scopes 实时计算（超管返回全部 scope）
 * - 用于前端按 scope 控制导航和页面可见性
 */
export const readUserMeV1UsersMeGet = <ThrowOnError extends boolean = false>(options?: Options<ReadUserMeV1UsersMeGetData, ThrowOnError>) => (options?.client ?? client).get<ReadUserMeV1UsersMeGetResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/users/me',
    ...options
});

/**
 * Update User Me
 *
 * 更新当前用户自己的信息。
 *
 * 权限：登录用户（自己的账户）
 *
 * 参数：
 * - session：数据库会话
 * - user_in：用户更新 DTO（full_name、email 可选）
 * - current_user：当前登录用户（依赖注入）
 *
 * 返回值：
 * - UserPublic：更新后的用户信息（含 scopes）
 *
 * 业务逻辑：
 * 1. 若修改邮箱，检查新邮箱是否被其他用户占用
 * 2. 使用 model_dump(exclude_unset=True) 仅获取用户明确设置的字段
 * 3. 使用 sqlmodel_update() 合并更新
 * 4. 提交事务
 *
 * 邮箱冲突处理：
 * - 允许用户更新为自己的原邮箱
 * - 若邮箱被其他用户占用，返回 409 冲突错误
 */
export const updateUserMeV1UsersMePatch = <ThrowOnError extends boolean = false>(options: Options<UpdateUserMeV1UsersMePatchData, ThrowOnError>) => (options.client ?? client).patch<UpdateUserMeV1UsersMePatchResponses, UpdateUserMeV1UsersMePatchErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/users/me',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update Password Me
 *
 * 修改当前用户自己的密码。
 *
 * 权限：登录用户
 *
 * 参数：
 * - session：数据库会话
 * - body：密码更新 DTO（current_password、new_password）
 * - current_user：当前登录用户
 *
 * 返回值：
 * - Message：成功消息
 *
 * 业务流程：
 * 1. 验证现有密码是否正确（调用 verify_password）
 * 2. 检查新密码是否与旧密码相同（防止无意义操作）
 * 3. 哈希新密码并保存到数据库
 * 4. 返回成功消息
 *
 * 验证失败返回：
 * - 400：密码错误
 * - 400：新密码与旧密码相同
 */
export const updatePasswordMeV1UsersMePasswordPatch = <ThrowOnError extends boolean = false>(options: Options<UpdatePasswordMeV1UsersMePasswordPatchData, ThrowOnError>) => (options.client ?? client).patch<UpdatePasswordMeV1UsersMePasswordPatchResponses, UpdatePasswordMeV1UsersMePasswordPatchErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/users/me/password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Register User
 *
 * 用户自助注册（无需登录）。
 *
 * 权限：公开
 *
 * 参数：
 * - session：数据库会话
 * - user_in：用户注册 DTO（邮箱、密码、姓名）
 *
 * 返回值：
 * - UserPublic：创建的用户信息
 *
 * 业务流程：
 * 1. 检查邮箱是否已存在
 * 2. 使用 model_validate 将 UserRegister DTO 转换为 UserCreate DTO
 * 3. 调用 repository.create_user() 创建用户
 *
 * 异常：
 * - 409：邮箱已被注册
 *
 * 与 /users POST 的区别：
 * - 此路由无需超管权限，任何人可注册
 * - 此路由不发送邮件通知
 */
export const registerUserV1UsersSignupPost = <ThrowOnError extends boolean = false>(options: Options<RegisterUserV1UsersSignupPostData, ThrowOnError>) => (options.client ?? client).post<RegisterUserV1UsersSignupPostResponses, RegisterUserV1UsersSignupPostErrors, ThrowOnError>({
    url: '/v1/users/signup',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete User
 *
 * 删除指定用户（scope 判定，而非超管判定）。
 *
 * 权限：拥有 user:admin 或 user:delete scope（与用户管理删除按钮一致）。
 * - 超管本身拥有全部 scope，天然满足此权限。
 * - 普通拥有 user:delete scope 的角色（如 editor）也可删除用户。
 *
 * 参数：
 * - session：数据库会话
 * - current_user：当前用户（用于禁止删除自己）
 * - user_id：目标用户 UUID
 *
 * 返回值：
 * - Message：删除成功消息
 *
 * 异常：
 * - 404：用户不存在
 * - 403：不允许删除自己
 * - 403：无 user:admin / user:delete scope
 *
 * 注意：
 * - User.roles 多对多关联的表 userrole 外键为 ondelete="CASCADE"，
 * 删除用户时数据库会自动清理其与角色的关联。
 */
export const deleteUserV1UsersUserIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteUserV1UsersUserIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<DeleteUserV1UsersUserIdDeleteResponses, DeleteUserV1UsersUserIdDeleteErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/users/{user_id}',
    ...options
});

/**
 * Read User By Id
 *
 * 获取指定用户信息。
 *
 * 权限：拥有 user:read scope。
 *
 * 参数：
 * - user_id：目标用户 UUID
 * - session：数据库会话
 * - current_user：当前登录用户
 *
 * 返回值：
 * - UserPublic：用户信息
 *
 * 业务流程：
 * 1. 查询指定用户
 * 2. 若不存在，返回 404
 *
 * 异常：
 * - 403：无 user:read scope
 * - 404：用户不存在
 */
export const readUserByIdV1UsersUserIdGet = <ThrowOnError extends boolean = false>(options: Options<ReadUserByIdV1UsersUserIdGetData, ThrowOnError>) => (options.client ?? client).get<ReadUserByIdV1UsersUserIdGetResponses, ReadUserByIdV1UsersUserIdGetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/users/{user_id}',
    ...options
});

/**
 * Update User
 *
 * 更新指定用户信息（scope 判定）。
 *
 * 权限：拥有 user:update scope。
 *
 * 参数：
 * - session：数据库会话
 * - user_id：目标用户 UUID
 * - user_in：用户更新 DTO（email、password、is_active、is_superuser 等可选）
 *
 * 返回值：
 * - UserPublic：更新后的用户信息
 *
 * 业务流程：
 * 1. 查询目标用户是否存在
 * 2. 若修改邮箱，检查新邮箱唯一性（允许保持原邮箱）
 * 3. 调用 repository.update_user() 更新用户
 * 4. 返回更新后的用户
 *
 * 异常：
 * - 404：用户不存在
 * - 409：新邮箱被其他用户占用
 * - 403：无 user:update scope
 */
export const updateUserV1UsersUserIdPatch = <ThrowOnError extends boolean = false>(options: Options<UpdateUserV1UsersUserIdPatchData, ThrowOnError>) => (options.client ?? client).patch<UpdateUserV1UsersUserIdPatchResponses, UpdateUserV1UsersUserIdPatchErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/users/{user_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read Roles
 *
 * 获取角色列表（分页）。
 *
 * 权限：拥有 role:read scope。
 *
 * 返回：
 * - RolesPublic：data（角色列表，含 scopes）、count、page、page_size、total_pages
 */
export const readRolesV1RolesGet = <ThrowOnError extends boolean = false>(options?: Options<ReadRolesV1RolesGetData, ThrowOnError>) => (options?.client ?? client).get<ReadRolesV1RolesGetResponses, ReadRolesV1RolesGetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/roles/',
    ...options
});

/**
 * Create Role
 *
 * 创建新角色。
 *
 * 权限：拥有 role:create scope。
 *
 * 参数：
 * - role_in：RoleCreate（name 必填，scopes 可选）
 *
 * 异常：
 * - 409：角色名已存在
 * - 400：包含未定义的 scope
 */
export const createRoleV1RolesPost = <ThrowOnError extends boolean = false>(options: Options<CreateRoleV1RolesPostData, ThrowOnError>) => (options.client ?? client).post<CreateRoleV1RolesPostResponses, CreateRoleV1RolesPostErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/roles/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Role
 *
 * 删除角色。
 *
 * 权限：拥有 role:delete scope。
 *
 * 注意：
 * - 系统预置角色（viewer / editor / admin）不允许删除。
 * - 角色删除后，引用它的用户会自动解除关联（UserRole 外键 CASCADE）。
 *
 * 异常：
 * - 404：角色不存在
 * - 400：删除预置角色
 */
export const deleteRoleV1RolesRoleIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteRoleV1RolesRoleIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<DeleteRoleV1RolesRoleIdDeleteResponses, DeleteRoleV1RolesRoleIdDeleteErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/roles/{role_id}',
    ...options
});

/**
 * Read Role
 *
 * 获取单个角色详情（含 scopes 列表）。
 *
 * 权限：拥有 role:read scope。
 */
export const readRoleV1RolesRoleIdGet = <ThrowOnError extends boolean = false>(options: Options<ReadRoleV1RolesRoleIdGetData, ThrowOnError>) => (options.client ?? client).get<ReadRoleV1RolesRoleIdGetResponses, ReadRoleV1RolesRoleIdGetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/roles/{role_id}',
    ...options
});

/**
 * Update Role
 *
 * 更新角色（修改名字和/或它的 scope 集合）。
 *
 * 权限：拥有 role:update scope。
 *
 * 参数：
 * - role_id：目标角色 UUID
 * - role_in：RoleUpdate（name、scopes 均可选）
 *
 * 业务规则：
 * - 传入 scopes 时整体替换（先删后插），实现增减权限的效果。
 * - 系统预置角色（viewer / editor / admin）不允许修改。
 *
 * 异常：
 * - 404：角色不存在
 * - 400：角色名与其他角色冲突 / 包含未定义 scope / 修改预置角色
 */
export const updateRoleV1RolesRoleIdPatch = <ThrowOnError extends boolean = false>(options: Options<UpdateRoleV1RolesRoleIdPatchData, ThrowOnError>) => (options.client ?? client).patch<UpdateRoleV1RolesRoleIdPatchResponses, UpdateRoleV1RolesRoleIdPatchErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/roles/{role_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
