// This file is auto-generated by @hey-api/openapi-ts

export type BodyLoginAccessTokenV1LoginAccessTokenPost = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: string | null;
};

export type ItemPublic = {
    title: string;
    description?: string | null;
    id: string;
    owner_id: string;
    created_at?: string | null;
};

export type ItemUpdate = {
    title?: string | null;
    description?: string | null;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: string | null;
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: string | null;
    id: string;
    created_at?: string | null;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: string | null;
};

export type UserUpdate = {
    email?: string | null;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: string | null;
    password?: string | null;
};

export type UserUpdateMe = {
    full_name?: string | null;
    email?: string | null;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type LoginAccessTokenV1LoginAccessTokenPostData = {
    body: BodyLoginAccessTokenV1LoginAccessTokenPost;
    path?: never;
    query?: never;
    url: '/v1/login/access-token';
};

export type LoginAccessTokenV1LoginAccessTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAccessTokenV1LoginAccessTokenPostError = LoginAccessTokenV1LoginAccessTokenPostErrors[keyof LoginAccessTokenV1LoginAccessTokenPostErrors];

export type LoginAccessTokenV1LoginAccessTokenPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginAccessTokenV1LoginAccessTokenPostResponse = LoginAccessTokenV1LoginAccessTokenPostResponses[keyof LoginAccessTokenV1LoginAccessTokenPostResponses];

export type TestTokenV1LoginTestTokenPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/login/test-token';
};

export type TestTokenV1LoginTestTokenPostResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type TestTokenV1LoginTestTokenPostResponse = TestTokenV1LoginTestTokenPostResponses[keyof TestTokenV1LoginTestTokenPostResponses];

export type ResetPasswordV1ResetPasswordPostData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/v1/reset-password/';
};

export type ResetPasswordV1ResetPasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetPasswordV1ResetPasswordPostError = ResetPasswordV1ResetPasswordPostErrors[keyof ResetPasswordV1ResetPasswordPostErrors];

export type ResetPasswordV1ResetPasswordPostResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ResetPasswordV1ResetPasswordPostResponse = ResetPasswordV1ResetPasswordPostResponses[keyof ResetPasswordV1ResetPasswordPostResponses];

export type ReadUsersV1UsersUsersGetData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        limit?: number;
    };
    url: '/v1/users/users/';
};

export type ReadUsersV1UsersUsersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUsersV1UsersUsersGetError = ReadUsersV1UsersUsersGetErrors[keyof ReadUsersV1UsersUsersGetErrors];

export type ReadUsersV1UsersUsersGetResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type ReadUsersV1UsersUsersGetResponse = ReadUsersV1UsersUsersGetResponses[keyof ReadUsersV1UsersUsersGetResponses];

export type CreateUserV1UsersUsersPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/v1/users/users/';
};

export type CreateUserV1UsersUsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserV1UsersUsersPostError = CreateUserV1UsersUsersPostErrors[keyof CreateUserV1UsersUsersPostErrors];

export type CreateUserV1UsersUsersPostResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type CreateUserV1UsersUsersPostResponse = CreateUserV1UsersUsersPostResponses[keyof CreateUserV1UsersUsersPostResponses];

export type DeleteUserMeV1UsersUsersMeDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/users/users/me';
};

export type DeleteUserMeV1UsersUsersMeDeleteResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteUserMeV1UsersUsersMeDeleteResponse = DeleteUserMeV1UsersUsersMeDeleteResponses[keyof DeleteUserMeV1UsersUsersMeDeleteResponses];

export type ReadUserMeV1UsersUsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/users/users/me';
};

export type ReadUserMeV1UsersUsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type ReadUserMeV1UsersUsersMeGetResponse = ReadUserMeV1UsersUsersMeGetResponses[keyof ReadUserMeV1UsersUsersMeGetResponses];

export type UpdateUserMeV1UsersUsersMePatchData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/v1/users/users/me';
};

export type UpdateUserMeV1UsersUsersMePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserMeV1UsersUsersMePatchError = UpdateUserMeV1UsersUsersMePatchErrors[keyof UpdateUserMeV1UsersUsersMePatchErrors];

export type UpdateUserMeV1UsersUsersMePatchResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UpdateUserMeV1UsersUsersMePatchResponse = UpdateUserMeV1UsersUsersMePatchResponses[keyof UpdateUserMeV1UsersUsersMePatchResponses];

export type UpdatePasswordMeV1UsersUsersMePasswordPatchData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/v1/users/users/me/password';
};

export type UpdatePasswordMeV1UsersUsersMePasswordPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePasswordMeV1UsersUsersMePasswordPatchError = UpdatePasswordMeV1UsersUsersMePasswordPatchErrors[keyof UpdatePasswordMeV1UsersUsersMePasswordPatchErrors];

export type UpdatePasswordMeV1UsersUsersMePasswordPatchResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UpdatePasswordMeV1UsersUsersMePasswordPatchResponse = UpdatePasswordMeV1UsersUsersMePasswordPatchResponses[keyof UpdatePasswordMeV1UsersUsersMePasswordPatchResponses];

export type RegisterUserV1UsersUsersSignupPostData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/v1/users/users/signup';
};

export type RegisterUserV1UsersUsersSignupPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterUserV1UsersUsersSignupPostError = RegisterUserV1UsersUsersSignupPostErrors[keyof RegisterUserV1UsersUsersSignupPostErrors];

export type RegisterUserV1UsersUsersSignupPostResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type RegisterUserV1UsersUsersSignupPostResponse = RegisterUserV1UsersUsersSignupPostResponses[keyof RegisterUserV1UsersUsersSignupPostResponses];

export type DeleteUserV1UsersUsersUserIdDeleteData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/v1/users/users/{user_id}';
};

export type DeleteUserV1UsersUsersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserV1UsersUsersUserIdDeleteError = DeleteUserV1UsersUsersUserIdDeleteErrors[keyof DeleteUserV1UsersUsersUserIdDeleteErrors];

export type DeleteUserV1UsersUsersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteUserV1UsersUsersUserIdDeleteResponse = DeleteUserV1UsersUsersUserIdDeleteResponses[keyof DeleteUserV1UsersUsersUserIdDeleteResponses];

export type ReadUserByIdV1UsersUsersUserIdGetData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/v1/users/users/{user_id}';
};

export type ReadUserByIdV1UsersUsersUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUserByIdV1UsersUsersUserIdGetError = ReadUserByIdV1UsersUsersUserIdGetErrors[keyof ReadUserByIdV1UsersUsersUserIdGetErrors];

export type ReadUserByIdV1UsersUsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type ReadUserByIdV1UsersUsersUserIdGetResponse = ReadUserByIdV1UsersUsersUserIdGetResponses[keyof ReadUserByIdV1UsersUsersUserIdGetResponses];

export type UpdateUserV1UsersUsersUserIdPatchData = {
    body: UserUpdate;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/v1/users/users/{user_id}';
};

export type UpdateUserV1UsersUsersUserIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserV1UsersUsersUserIdPatchError = UpdateUserV1UsersUsersUserIdPatchErrors[keyof UpdateUserV1UsersUsersUserIdPatchErrors];

export type UpdateUserV1UsersUsersUserIdPatchResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UpdateUserV1UsersUsersUserIdPatchResponse = UpdateUserV1UsersUsersUserIdPatchResponses[keyof UpdateUserV1UsersUsersUserIdPatchResponses];

export type HealthCheckV1UsersUsersHealthCheckGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/users/users/health-check/';
};

export type HealthCheckV1UsersUsersHealthCheckGetResponses = {
    /**
     * Successful Response
     */
    200: boolean;
};

export type HealthCheckV1UsersUsersHealthCheckGetResponse = HealthCheckV1UsersUsersHealthCheckGetResponses[keyof HealthCheckV1UsersUsersHealthCheckGetResponses];

export type ReadItemsV1ItemsItemsGetData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        limit?: number;
    };
    url: '/v1/items/items/';
};

export type ReadItemsV1ItemsItemsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadItemsV1ItemsItemsGetError = ReadItemsV1ItemsItemsGetErrors[keyof ReadItemsV1ItemsItemsGetErrors];

export type ReadItemsV1ItemsItemsGetResponses = {
    /**
     * Successful Response
     */
    200: ItemsPublic;
};

export type ReadItemsV1ItemsItemsGetResponse = ReadItemsV1ItemsItemsGetResponses[keyof ReadItemsV1ItemsItemsGetResponses];

export type CreateItemV1ItemsItemsPostData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/v1/items/items/';
};

export type CreateItemV1ItemsItemsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateItemV1ItemsItemsPostError = CreateItemV1ItemsItemsPostErrors[keyof CreateItemV1ItemsItemsPostErrors];

export type CreateItemV1ItemsItemsPostResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type CreateItemV1ItemsItemsPostResponse = CreateItemV1ItemsItemsPostResponses[keyof CreateItemV1ItemsItemsPostResponses];

export type DeleteItemV1ItemsItemsIdDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/items/items/{id}';
};

export type DeleteItemV1ItemsItemsIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteItemV1ItemsItemsIdDeleteError = DeleteItemV1ItemsItemsIdDeleteErrors[keyof DeleteItemV1ItemsItemsIdDeleteErrors];

export type DeleteItemV1ItemsItemsIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteItemV1ItemsItemsIdDeleteResponse = DeleteItemV1ItemsItemsIdDeleteResponses[keyof DeleteItemV1ItemsItemsIdDeleteResponses];

export type ReadItemV1ItemsItemsIdGetData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/items/items/{id}';
};

export type ReadItemV1ItemsItemsIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadItemV1ItemsItemsIdGetError = ReadItemV1ItemsItemsIdGetErrors[keyof ReadItemV1ItemsItemsIdGetErrors];

export type ReadItemV1ItemsItemsIdGetResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ReadItemV1ItemsItemsIdGetResponse = ReadItemV1ItemsItemsIdGetResponses[keyof ReadItemV1ItemsItemsIdGetResponses];

export type UpdateItemV1ItemsItemsIdPutData = {
    body: ItemUpdate;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/items/items/{id}';
};

export type UpdateItemV1ItemsItemsIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateItemV1ItemsItemsIdPutError = UpdateItemV1ItemsItemsIdPutErrors[keyof UpdateItemV1ItemsItemsIdPutErrors];

export type UpdateItemV1ItemsItemsIdPutResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type UpdateItemV1ItemsItemsIdPutResponse = UpdateItemV1ItemsItemsIdPutResponses[keyof UpdateItemV1ItemsItemsIdPutResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};