// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Body_login_access_token_v1_login_access_token_post
 */
export type BodyLoginAccessTokenV1LoginAccessTokenPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemsPublic
 */
export type ItemsPublic = {
    /**
     * Data
     */
    data: Array<ItemPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type LoginAccessTokenV1LoginAccessTokenPostData = {
    body: BodyLoginAccessTokenV1LoginAccessTokenPost;
    path?: never;
    query?: never;
    url: '/v1/login/access-token';
};

export type LoginAccessTokenV1LoginAccessTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAccessTokenV1LoginAccessTokenPostError = LoginAccessTokenV1LoginAccessTokenPostErrors[keyof LoginAccessTokenV1LoginAccessTokenPostErrors];

export type LoginAccessTokenV1LoginAccessTokenPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginAccessTokenV1LoginAccessTokenPostResponse = LoginAccessTokenV1LoginAccessTokenPostResponses[keyof LoginAccessTokenV1LoginAccessTokenPostResponses];

export type TestTokenV1LoginTestTokenPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/login/test-token';
};

export type TestTokenV1LoginTestTokenPostResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type TestTokenV1LoginTestTokenPostResponse = TestTokenV1LoginTestTokenPostResponses[keyof TestTokenV1LoginTestTokenPostResponses];

export type ResetPasswordV1ResetPasswordPostData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/v1/reset-password/';
};

export type ResetPasswordV1ResetPasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetPasswordV1ResetPasswordPostError = ResetPasswordV1ResetPasswordPostErrors[keyof ResetPasswordV1ResetPasswordPostErrors];

export type ResetPasswordV1ResetPasswordPostResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ResetPasswordV1ResetPasswordPostResponse = ResetPasswordV1ResetPasswordPostResponses[keyof ResetPasswordV1ResetPasswordPostResponses];

export type ReadUsersV1UsersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/v1/users/';
};

export type ReadUsersV1UsersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUsersV1UsersGetError = ReadUsersV1UsersGetErrors[keyof ReadUsersV1UsersGetErrors];

export type ReadUsersV1UsersGetResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type ReadUsersV1UsersGetResponse = ReadUsersV1UsersGetResponses[keyof ReadUsersV1UsersGetResponses];

export type CreateUserV1UsersPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/v1/users/';
};

export type CreateUserV1UsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserV1UsersPostError = CreateUserV1UsersPostErrors[keyof CreateUserV1UsersPostErrors];

export type CreateUserV1UsersPostResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type CreateUserV1UsersPostResponse = CreateUserV1UsersPostResponses[keyof CreateUserV1UsersPostResponses];

export type DeleteUserMeV1UsersMeDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/users/me';
};

export type DeleteUserMeV1UsersMeDeleteResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteUserMeV1UsersMeDeleteResponse = DeleteUserMeV1UsersMeDeleteResponses[keyof DeleteUserMeV1UsersMeDeleteResponses];

export type ReadUserMeV1UsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/users/me';
};

export type ReadUserMeV1UsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type ReadUserMeV1UsersMeGetResponse = ReadUserMeV1UsersMeGetResponses[keyof ReadUserMeV1UsersMeGetResponses];

export type UpdateUserMeV1UsersMePatchData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/v1/users/me';
};

export type UpdateUserMeV1UsersMePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserMeV1UsersMePatchError = UpdateUserMeV1UsersMePatchErrors[keyof UpdateUserMeV1UsersMePatchErrors];

export type UpdateUserMeV1UsersMePatchResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UpdateUserMeV1UsersMePatchResponse = UpdateUserMeV1UsersMePatchResponses[keyof UpdateUserMeV1UsersMePatchResponses];

export type UpdatePasswordMeV1UsersMePasswordPatchData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/v1/users/me/password';
};

export type UpdatePasswordMeV1UsersMePasswordPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePasswordMeV1UsersMePasswordPatchError = UpdatePasswordMeV1UsersMePasswordPatchErrors[keyof UpdatePasswordMeV1UsersMePasswordPatchErrors];

export type UpdatePasswordMeV1UsersMePasswordPatchResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UpdatePasswordMeV1UsersMePasswordPatchResponse = UpdatePasswordMeV1UsersMePasswordPatchResponses[keyof UpdatePasswordMeV1UsersMePasswordPatchResponses];

export type RegisterUserV1UsersSignupPostData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/v1/users/signup';
};

export type RegisterUserV1UsersSignupPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterUserV1UsersSignupPostError = RegisterUserV1UsersSignupPostErrors[keyof RegisterUserV1UsersSignupPostErrors];

export type RegisterUserV1UsersSignupPostResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type RegisterUserV1UsersSignupPostResponse = RegisterUserV1UsersSignupPostResponses[keyof RegisterUserV1UsersSignupPostResponses];

export type DeleteUserV1UsersUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/v1/users/{user_id}';
};

export type DeleteUserV1UsersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserV1UsersUserIdDeleteError = DeleteUserV1UsersUserIdDeleteErrors[keyof DeleteUserV1UsersUserIdDeleteErrors];

export type DeleteUserV1UsersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteUserV1UsersUserIdDeleteResponse = DeleteUserV1UsersUserIdDeleteResponses[keyof DeleteUserV1UsersUserIdDeleteResponses];

export type ReadUserByIdV1UsersUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/v1/users/{user_id}';
};

export type ReadUserByIdV1UsersUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUserByIdV1UsersUserIdGetError = ReadUserByIdV1UsersUserIdGetErrors[keyof ReadUserByIdV1UsersUserIdGetErrors];

export type ReadUserByIdV1UsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type ReadUserByIdV1UsersUserIdGetResponse = ReadUserByIdV1UsersUserIdGetResponses[keyof ReadUserByIdV1UsersUserIdGetResponses];

export type UpdateUserV1UsersUserIdPatchData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/v1/users/{user_id}';
};

export type UpdateUserV1UsersUserIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserV1UsersUserIdPatchError = UpdateUserV1UsersUserIdPatchErrors[keyof UpdateUserV1UsersUserIdPatchErrors];

export type UpdateUserV1UsersUserIdPatchResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UpdateUserV1UsersUserIdPatchResponse = UpdateUserV1UsersUserIdPatchResponses[keyof UpdateUserV1UsersUserIdPatchResponses];

export type HealthCheckV1UsersHealthCheckGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/users/health-check/';
};

export type HealthCheckV1UsersHealthCheckGetResponses = {
    /**
     * Response Health Check V1 Users Health Check  Get
     *
     * Successful Response
     */
    200: boolean;
};

export type HealthCheckV1UsersHealthCheckGetResponse = HealthCheckV1UsersHealthCheckGetResponses[keyof HealthCheckV1UsersHealthCheckGetResponses];

export type ReadItemsV1ItemsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/v1/items/';
};

export type ReadItemsV1ItemsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadItemsV1ItemsGetError = ReadItemsV1ItemsGetErrors[keyof ReadItemsV1ItemsGetErrors];

export type ReadItemsV1ItemsGetResponses = {
    /**
     * Successful Response
     */
    200: ItemsPublic;
};

export type ReadItemsV1ItemsGetResponse = ReadItemsV1ItemsGetResponses[keyof ReadItemsV1ItemsGetResponses];

export type CreateItemV1ItemsPostData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/v1/items/';
};

export type CreateItemV1ItemsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateItemV1ItemsPostError = CreateItemV1ItemsPostErrors[keyof CreateItemV1ItemsPostErrors];

export type CreateItemV1ItemsPostResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type CreateItemV1ItemsPostResponse = CreateItemV1ItemsPostResponses[keyof CreateItemV1ItemsPostResponses];

export type DeleteItemV1ItemsIdDeleteData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/v1/items/{id}';
};

export type DeleteItemV1ItemsIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteItemV1ItemsIdDeleteError = DeleteItemV1ItemsIdDeleteErrors[keyof DeleteItemV1ItemsIdDeleteErrors];

export type DeleteItemV1ItemsIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteItemV1ItemsIdDeleteResponse = DeleteItemV1ItemsIdDeleteResponses[keyof DeleteItemV1ItemsIdDeleteResponses];

export type ReadItemV1ItemsIdGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/v1/items/{id}';
};

export type ReadItemV1ItemsIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadItemV1ItemsIdGetError = ReadItemV1ItemsIdGetErrors[keyof ReadItemV1ItemsIdGetErrors];

export type ReadItemV1ItemsIdGetResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ReadItemV1ItemsIdGetResponse = ReadItemV1ItemsIdGetResponses[keyof ReadItemV1ItemsIdGetResponses];

export type UpdateItemV1ItemsIdPutData = {
    body: ItemUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/v1/items/{id}';
};

export type UpdateItemV1ItemsIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateItemV1ItemsIdPutError = UpdateItemV1ItemsIdPutErrors[keyof UpdateItemV1ItemsIdPutErrors];

export type UpdateItemV1ItemsIdPutResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type UpdateItemV1ItemsIdPutResponse = UpdateItemV1ItemsIdPutResponses[keyof UpdateItemV1ItemsIdPutResponses];

export type TriggerErrorSentryDebugGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sentry-debug';
};

export type TriggerErrorSentryDebugGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
