// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * Body_login_access_token_v1_login_access_token_post
 */
export const zBodyLoginAccessTokenV1LoginAccessTokenPost = z.object({
    grant_type: z.string().regex(/^password$/).nullish(),
    username: z.string(),
    password: z.string(),
    scope: z.string().optional().default(''),
    client_id: z.string().nullish(),
    client_secret: z.string().nullish()
});

/**
 * Message
 *
 * 通用消息响应
 */
export const zMessage = z.object({
    message: z.string()
});

/**
 * RoleCreate
 *
 * 创建角色的请求体：name 必填，scopes 可选（默认空集合）
 */
export const zRoleCreate = z.object({
    name: z.string().min(1).max(50),
    scopes: z.array(z.string()).max(100).optional()
});

/**
 * RolePublic
 *
 * 单条角色的响应体：基础字段 + 当前持有的 scope 列表
 */
export const zRolePublic = z.object({
    id: z.uuid(),
    name: z.string(),
    created_at: z.iso.datetime().nullish(),
    scopes: z.array(z.string()).optional()
});

/**
 * RoleUpdate
 *
 * 更新角色的请求体：所有字段可选，未设置的字段保持不变（部分更新）
 *
 * - name：角色名（更新后会影响引用此角色的用户）
 * - scopes：完整的 scope 集合（整体替换，非增量合并）
 */
export const zRoleUpdate = z.object({
    name: z.string().min(1).max(50).nullish(),
    scopes: z.array(z.string()).max(100).nullish()
});

/**
 * RolesPublic
 *
 * 角色分页列表的响应体：data / count / page / page_size / total_pages
 */
export const zRolesPublic = z.object({
    data: z.array(z.unknown()),
    count: z.int(),
    page: z.int().nullish(),
    page_size: z.int().nullish(),
    total_pages: z.int().nullish()
});

/**
 * Token
 */
export const zToken = z.object({
    access_token: z.string(),
    token_type: z.string().optional().default('bearer')
});

/**
 * UpdatePassword
 */
export const zUpdatePassword = z.object({
    current_password: z.string().min(8).max(128),
    new_password: z.string().min(8).max(128)
});

/**
 * UserCreate
 */
export const zUserCreate = z.object({
    email: z.email().max(255),
    is_active: z.boolean().optional().default(true),
    is_superuser: z.boolean().optional().default(false),
    full_name: z.string().max(255).nullish(),
    password: z.string().min(8).max(128)
});

/**
 * UserPublic
 */
export const zUserPublic = z.object({
    email: z.email().max(255),
    is_active: z.boolean().optional().default(true),
    is_superuser: z.boolean().optional().default(false),
    full_name: z.string().max(255).nullish(),
    id: z.uuid(),
    created_at: z.iso.datetime().nullish(),
    scopes: z.array(z.string()).optional()
});

/**
 * UserRegister
 */
export const zUserRegister = z.object({
    email: z.email().max(255),
    password: z.string().min(8).max(128),
    full_name: z.string().max(255).nullish()
});

/**
 * UserUpdate
 */
export const zUserUpdate = z.object({
    email: z.email().max(255).nullish(),
    is_active: z.boolean().nullish(),
    is_superuser: z.boolean().nullish(),
    full_name: z.string().max(255).nullish(),
    password: z.string().min(8).max(128).nullish()
});

/**
 * UserUpdateMe
 */
export const zUserUpdateMe = z.object({
    full_name: z.string().max(255).nullish(),
    email: z.email().max(255).nullish()
});

/**
 * UsersPublic
 */
export const zUsersPublic = z.object({
    data: z.array(z.unknown()),
    count: z.int(),
    page: z.int().nullish(),
    page_size: z.int().nullish(),
    total_pages: z.int().nullish()
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string(),
    input: z.unknown().optional(),
    ctx: z.record(z.string(), z.unknown()).optional()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

/**
 * Response Health Check V1 Health Check Get
 *
 * Successful Response
 */
export const zHealthCheckV1HealthCheckGetResponse = z.boolean();

export const zLoginAccessTokenV1LoginAccessTokenPostBody = zBodyLoginAccessTokenV1LoginAccessTokenPost;

/**
 * Successful Response
 */
export const zLoginAccessTokenV1LoginAccessTokenPostResponse = zToken;

/**
 * Successful Response
 */
export const zTestTokenV1LoginTestTokenPostResponse = zUserPublic;

export const zReadUsersV1UsersGetQuery = z.object({
    page: z.int().optional().default(1),
    page_size: z.int().optional().default(20)
});

/**
 * Successful Response
 */
export const zReadUsersV1UsersGetResponse = zUsersPublic;

export const zCreateUserV1UsersPostBody = zUserCreate;

/**
 * Successful Response
 */
export const zCreateUserV1UsersPostResponse = zUserPublic;

/**
 * Successful Response
 */
export const zDeleteUserMeV1UsersMeDeleteResponse = zMessage;

/**
 * Successful Response
 */
export const zReadUserMeV1UsersMeGetResponse = zUserPublic;

export const zUpdateUserMeV1UsersMePatchBody = zUserUpdateMe;

/**
 * Successful Response
 */
export const zUpdateUserMeV1UsersMePatchResponse = zUserPublic;

export const zUpdatePasswordMeV1UsersMePasswordPatchBody = zUpdatePassword;

/**
 * Successful Response
 */
export const zUpdatePasswordMeV1UsersMePasswordPatchResponse = zMessage;

export const zRegisterUserV1UsersSignupPostBody = zUserRegister;

/**
 * Successful Response
 */
export const zRegisterUserV1UsersSignupPostResponse = zUserPublic;

export const zDeleteUserV1UsersUserIdDeletePath = z.object({
    user_id: z.uuid()
});

/**
 * Successful Response
 */
export const zDeleteUserV1UsersUserIdDeleteResponse = zMessage;

export const zReadUserByIdV1UsersUserIdGetPath = z.object({
    user_id: z.uuid()
});

/**
 * Successful Response
 */
export const zReadUserByIdV1UsersUserIdGetResponse = zUserPublic;

export const zUpdateUserV1UsersUserIdPatchBody = zUserUpdate;

export const zUpdateUserV1UsersUserIdPatchPath = z.object({
    user_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateUserV1UsersUserIdPatchResponse = zUserPublic;

export const zReadRolesV1RolesGetQuery = z.object({
    page: z.int().optional().default(1),
    page_size: z.int().optional().default(20)
});

/**
 * Successful Response
 */
export const zReadRolesV1RolesGetResponse = zRolesPublic;

export const zCreateRoleV1RolesPostBody = zRoleCreate;

/**
 * Successful Response
 */
export const zCreateRoleV1RolesPostResponse = zRolePublic;

export const zDeleteRoleV1RolesRoleIdDeletePath = z.object({
    role_id: z.uuid()
});

/**
 * Successful Response
 */
export const zDeleteRoleV1RolesRoleIdDeleteResponse = zMessage;

export const zReadRoleV1RolesRoleIdGetPath = z.object({
    role_id: z.uuid()
});

/**
 * Successful Response
 */
export const zReadRoleV1RolesRoleIdGetResponse = zRolePublic;

export const zUpdateRoleV1RolesRoleIdPatchBody = zRoleUpdate;

export const zUpdateRoleV1RolesRoleIdPatchPath = z.object({
    role_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateRoleV1RolesRoleIdPatchResponse = zRolePublic;
