// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * ArchivePostBrief
 *
 * 归档文章简要信息
 */
export const zArchivePostBrief = z.object({
    slug: z.string(),
    title: z.string(),
    published_at: z.iso.datetime().nullish()
});

/**
 * ArchiveEntry
 *
 * 单条归档记录（某年某月）
 */
export const zArchiveEntry = z.object({
    year: z.int(),
    month: z.int(),
    posts: z.array(zArchivePostBrief)
});

/**
 * ArchiveResponse
 *
 * 归档响应
 */
export const zArchiveResponse = z.object({
    archives: z.array(zArchiveEntry)
});

/**
 * Body_login_access_token_v1_login_access_token_post
 */
export const zBodyLoginAccessTokenV1LoginAccessTokenPost = z.object({
    grant_type: z.string().regex(/^password$/).nullish(),
    username: z.string(),
    password: z.string(),
    scope: z.string().optional().default(''),
    client_id: z.string().nullish(),
    client_secret: z.string().nullish()
});

/**
 * CategoriesPublic
 *
 * 分类分页响应
 */
export const zCategoriesPublic = z.object({
    data: z.array(z.unknown()),
    count: z.int(),
    page: z.int().nullish(),
    page_size: z.int().nullish(),
    total_pages: z.int().nullish()
});

/**
 * CategoryCreate
 *
 * 创建分类请求
 */
export const zCategoryCreate = z.object({
    name: z.string().max(50),
    slug: z.string().max(50)
});

/**
 * CategoryPublic
 *
 * 公开分类响应（含文章计数）
 */
export const zCategoryPublic = z.object({
    name: z.string().max(50),
    slug: z.string().max(50),
    id: z.uuid(),
    post_count: z.int().optional().default(0),
    created_at: z.iso.datetime().nullish()
});

/**
 * CategoryUpdate
 *
 * 更新分类请求（所有字段可选）
 */
export const zCategoryUpdate = z.object({
    name: z.string().max(50).nullish(),
    slug: z.string().max(50).nullish()
});

/**
 * CommentCreate
 *
 * 创建评论请求
 */
export const zCommentCreate = z.object({
    author_name: z.string().max(80),
    content: z.string()
});

/**
 * CommentPublic
 *
 * 公开评论响应
 */
export const zCommentPublic = z.object({
    id: z.uuid(),
    post_id: z.uuid(),
    author_id: z.uuid().nullish(),
    author_name: z.string(),
    content: z.string(),
    created_at: z.iso.datetime().nullish()
});

/**
 * CommentsPublic
 *
 * 评论分页响应
 */
export const zCommentsPublic = z.object({
    data: z.array(z.unknown()),
    count: z.int(),
    page: z.int().nullish(),
    page_size: z.int().nullish(),
    total_pages: z.int().nullish()
});

/**
 * ItemCreate
 */
export const zItemCreate = z.object({
    title: z.string().min(1).max(255),
    description: z.string().max(255).nullish()
});

/**
 * ItemPublic
 */
export const zItemPublic = z.object({
    title: z.string().min(1).max(255),
    description: z.string().max(255).nullish(),
    id: z.uuid(),
    owner_id: z.uuid(),
    created_at: z.iso.datetime().nullish()
});

/**
 * ItemUpdate
 */
export const zItemUpdate = z.object({
    title: z.string().min(1).max(255).nullish(),
    description: z.string().max(255).nullish()
});

/**
 * ItemsPublic
 */
export const zItemsPublic = z.object({
    data: z.array(z.unknown()),
    count: z.int(),
    page: z.int().nullish(),
    page_size: z.int().nullish(),
    total_pages: z.int().nullish()
});

/**
 * Message
 *
 * 通用消息响应
 */
export const zMessage = z.object({
    message: z.string()
});

/**
 * PaginationParams
 *
 * 分页查询参数
 *
 * 用于统一分页请求参数:
 * - page: 页码，从 1 开始
 * - page_size: 每页数量，默认 20，最大 100
 */
export const zPaginationParams = z.object({
    page: z.int().optional().default(1),
    page_size: z.int().optional().default(20)
});

/**
 * PostCreate
 *
 * 创建文章请求
 */
export const zPostCreate = z.object({
    slug: z.string().max(255),
    title: z.string().max(255),
    excerpt: z.string().max(500).nullish(),
    body: z.string(),
    is_published: z.boolean().optional().default(false),
    category_id: z.uuid().nullish(),
    published_at: z.iso.datetime().nullish()
});

/**
 * PostDetailPublic
 *
 * 文章详情响应（包含 body）
 */
export const zPostDetailPublic = z.object({
    id: z.uuid(),
    slug: z.string(),
    title: z.string(),
    excerpt: z.string().nullish(),
    is_published: z.boolean(),
    category_id: z.uuid().nullish(),
    category: zCategoryPublic.nullish(),
    author_id: z.uuid(),
    author_name: z.string().nullish(),
    comments_count: z.int().optional().default(0),
    published_at: z.iso.datetime().nullish(),
    created_at: z.iso.datetime().nullish(),
    updated_at: z.iso.datetime().nullish(),
    body: z.string()
});

/**
 * PostPublic
 *
 * 公开文章响应（列表视图，不含 body）
 */
export const zPostPublic = z.object({
    id: z.uuid(),
    slug: z.string(),
    title: z.string(),
    excerpt: z.string().nullish(),
    is_published: z.boolean(),
    category_id: z.uuid().nullish(),
    category: zCategoryPublic.nullish(),
    author_id: z.uuid(),
    author_name: z.string().nullish(),
    comments_count: z.int().optional().default(0),
    published_at: z.iso.datetime().nullish(),
    created_at: z.iso.datetime().nullish(),
    updated_at: z.iso.datetime().nullish()
});

/**
 * PostUpdate
 *
 * 更新文章请求（所有字段可选）
 */
export const zPostUpdate = z.object({
    slug: z.string().max(255).nullish(),
    title: z.string().max(255).nullish(),
    excerpt: z.string().max(500).nullish(),
    body: z.string().nullish(),
    category_id: z.uuid().nullish(),
    is_published: z.boolean().nullish(),
    published_at: z.iso.datetime().nullish()
});

/**
 * PostsPublic
 *
 * 文章分页响应
 */
export const zPostsPublic = z.object({
    data: z.array(z.unknown()),
    count: z.int(),
    page: z.int().nullish(),
    page_size: z.int().nullish(),
    total_pages: z.int().nullish()
});

/**
 * RecentCommentPublic
 *
 * 最近评论响应（用于侧栏）
 */
export const zRecentCommentPublic = z.object({
    id: z.uuid(),
    author_name: z.string(),
    post_slug: z.string(),
    post_title: z.string(),
    content: z.string(),
    created_at: z.iso.datetime().nullish()
});

/**
 * Token
 */
export const zToken = z.object({
    access_token: z.string(),
    token_type: z.string().optional().default('bearer')
});

/**
 * UpdatePassword
 */
export const zUpdatePassword = z.object({
    current_password: z.string().min(8).max(128),
    new_password: z.string().min(8).max(128)
});

/**
 * UserCreate
 */
export const zUserCreate = z.object({
    email: z.email().max(255),
    username: z.string().min(3).max(50),
    is_active: z.boolean().optional().default(true),
    is_superuser: z.boolean().optional().default(false),
    full_name: z.string().max(255).nullish(),
    password: z.string().min(8).max(128)
});

/**
 * UserPublic
 */
export const zUserPublic = z.object({
    email: z.email().max(255),
    username: z.string().min(3).max(50),
    is_active: z.boolean().optional().default(true),
    is_superuser: z.boolean().optional().default(false),
    full_name: z.string().max(255).nullish(),
    id: z.uuid(),
    created_at: z.iso.datetime().nullish()
});

/**
 * UserRegister
 */
export const zUserRegister = z.object({
    email: z.email().max(255),
    username: z.string().min(3).max(50),
    password: z.string().min(8).max(128),
    full_name: z.string().max(255).nullish()
});

/**
 * UserUpdate
 */
export const zUserUpdate = z.object({
    email: z.email().max(255).nullish(),
    username: z.string().min(3).max(50).nullish(),
    is_active: z.boolean().optional().default(true),
    is_superuser: z.boolean().optional().default(false),
    full_name: z.string().max(255).nullish(),
    password: z.string().min(8).max(128).nullish()
});

/**
 * UserUpdateMe
 */
export const zUserUpdateMe = z.object({
    full_name: z.string().max(255).nullish(),
    email: z.email().max(255).nullish()
});

/**
 * UsersPublic
 */
export const zUsersPublic = z.object({
    data: z.array(z.unknown()),
    count: z.int(),
    page: z.int().nullish(),
    page_size: z.int().nullish(),
    total_pages: z.int().nullish()
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

export const zLoginAccessTokenV1LoginAccessTokenPostBody = zBodyLoginAccessTokenV1LoginAccessTokenPost;

/**
 * Successful Response
 */
export const zLoginAccessTokenV1LoginAccessTokenPostResponse = zToken;

/**
 * Successful Response
 */
export const zTestTokenV1LoginTestTokenPostResponse = zUserPublic;

export const zReadUsersV1UsersGetQuery = z.object({
    page: z.int().optional().default(1),
    page_size: z.int().optional().default(20)
});

/**
 * Successful Response
 */
export const zReadUsersV1UsersGetResponse = zUsersPublic;

export const zCreateUserV1UsersPostBody = zUserCreate;

/**
 * Successful Response
 */
export const zCreateUserV1UsersPostResponse = zUserPublic;

export const zDeleteUserV1UsersUserIdDeletePath = z.object({
    user_id: z.uuid()
});

/**
 * Successful Response
 */
export const zDeleteUserV1UsersUserIdDeleteResponse = zMessage;

export const zReadUserByIdV1UsersUserIdGetPath = z.object({
    user_id: z.uuid()
});

/**
 * Successful Response
 */
export const zReadUserByIdV1UsersUserIdGetResponse = zUserPublic;

export const zUpdateUserV1UsersUserIdPatchBody = zUserUpdate;

export const zUpdateUserV1UsersUserIdPatchPath = z.object({
    user_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateUserV1UsersUserIdPatchResponse = zUserPublic;

/**
 * Response Health Check V1 Users Health Check  Get
 *
 * Successful Response
 */
export const zHealthCheckV1UsersHealthCheckGetResponse = z.boolean();

/**
 * Successful Response
 */
export const zDeleteUserMeV1UsersMeDeleteResponse = zMessage;

/**
 * Successful Response
 */
export const zReadUserMeV1UsersMeGetResponse = zUserPublic;

export const zUpdateUserMeV1UsersMePatchBody = zUserUpdateMe;

/**
 * Successful Response
 */
export const zUpdateUserMeV1UsersMePatchResponse = zUserPublic;

export const zUpdatePasswordMeV1UsersMePasswordPatchBody = zUpdatePassword;

/**
 * Successful Response
 */
export const zUpdatePasswordMeV1UsersMePasswordPatchResponse = zMessage;

export const zRegisterUserV1UsersSignupPostBody = zUserRegister;

/**
 * Successful Response
 */
export const zRegisterUserV1UsersSignupPostResponse = zUserPublic;

export const zReadItemsV1ItemsGetQuery = z.object({
    page: z.int().optional().default(1),
    page_size: z.int().optional().default(20)
});

/**
 * Successful Response
 */
export const zReadItemsV1ItemsGetResponse = zItemsPublic;

export const zCreateItemV1ItemsPostBody = zItemCreate;

/**
 * Successful Response
 */
export const zCreateItemV1ItemsPostResponse = zItemPublic;

export const zDeleteItemV1ItemsItemIdDeletePath = z.object({
    item_id: z.uuid()
});

/**
 * Successful Response
 */
export const zDeleteItemV1ItemsItemIdDeleteResponse = zMessage;

export const zReadItemV1ItemsItemIdGetPath = z.object({
    item_id: z.uuid()
});

/**
 * Successful Response
 */
export const zReadItemV1ItemsItemIdGetResponse = zItemPublic;

export const zUpdateItemV1ItemsItemIdPutBody = zItemUpdate;

export const zUpdateItemV1ItemsItemIdPutPath = z.object({
    item_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateItemV1ItemsItemIdPutResponse = zItemPublic;

export const zListPostsV1BlogPostsGetQuery = z.object({
    pagination: zPaginationParams,
    q: z.string().nullish(),
    category: z.string().nullish()
});

/**
 * Successful Response
 */
export const zListPostsV1BlogPostsGetResponse = zPostsPublic;

export const zCreatePostV1BlogPostsPostBody = zPostCreate;

/**
 * Successful Response
 */
export const zCreatePostV1BlogPostsPostResponse = zPostPublic;

/**
 * Successful Response
 */
export const zGetArchivesV1BlogPostsArchivesGetResponse = zArchiveResponse;

export const zGetPostDetailV1BlogPostsSlugGetPath = z.object({
    slug: z.string()
});

/**
 * Successful Response
 */
export const zGetPostDetailV1BlogPostsSlugGetResponse = zPostDetailPublic;

export const zAdminListPostsV1BlogPostsAdminListGetQuery = z.object({
    pagination: zPaginationParams,
    q: z.string().nullish()
});

/**
 * Successful Response
 */
export const zAdminListPostsV1BlogPostsAdminListGetResponse = zPostsPublic;

export const zDeletePostV1BlogPostsPostIdDeletePath = z.object({
    post_id: z.uuid()
});

/**
 * Successful Response
 */
export const zDeletePostV1BlogPostsPostIdDeleteResponse = zMessage;

export const zUpdatePostV1BlogPostsPostIdPatchBody = zPostUpdate;

export const zUpdatePostV1BlogPostsPostIdPatchPath = z.object({
    post_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdatePostV1BlogPostsPostIdPatchResponse = zPostPublic;

export const zListCategoriesV1BlogCategoriesGetQuery = z.object({
    page: z.int().optional().default(1),
    page_size: z.int().optional().default(20)
});

/**
 * Successful Response
 */
export const zListCategoriesV1BlogCategoriesGetResponse = zCategoriesPublic;

export const zCreateCategoryV1BlogCategoriesPostBody = zCategoryCreate;

/**
 * Successful Response
 */
export const zCreateCategoryV1BlogCategoriesPostResponse = zCategoryPublic;

export const zListCategoryPostsV1BlogCategoriesSlugPostsGetPath = z.object({
    slug: z.string()
});

export const zListCategoryPostsV1BlogCategoriesSlugPostsGetQuery = z.object({
    page: z.int().optional().default(1),
    page_size: z.int().optional().default(20)
});

/**
 * Successful Response
 */
export const zListCategoryPostsV1BlogCategoriesSlugPostsGetResponse = zPostsPublic;

export const zDeleteCategoryV1BlogCategoriesCategoryIdDeletePath = z.object({
    category_id: z.uuid()
});

/**
 * Response Delete Category V1 Blog Categories  Category Id  Delete
 *
 * Successful Response
 */
export const zDeleteCategoryV1BlogCategoriesCategoryIdDeleteResponse = z.record(z.string(), z.unknown());

export const zUpdateCategoryV1BlogCategoriesCategoryIdPatchBody = zCategoryUpdate;

export const zUpdateCategoryV1BlogCategoriesCategoryIdPatchPath = z.object({
    category_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateCategoryV1BlogCategoriesCategoryIdPatchResponse = zCategoryPublic;

export const zListCommentsV1BlogPostsSlugCommentsGetPath = z.object({
    slug: z.string()
});

export const zListCommentsV1BlogPostsSlugCommentsGetQuery = z.object({
    page: z.int().optional().default(1),
    page_size: z.int().optional().default(20)
});

/**
 * Successful Response
 */
export const zListCommentsV1BlogPostsSlugCommentsGetResponse = zCommentsPublic;

export const zCreateCommentV1BlogPostsSlugCommentsPostBody = zCommentCreate;

export const zCreateCommentV1BlogPostsSlugCommentsPostPath = z.object({
    slug: z.string()
});

/**
 * Successful Response
 */
export const zCreateCommentV1BlogPostsSlugCommentsPostResponse = zCommentPublic;

export const zGetRecentCommentsV1BlogCommentsRecentGetQuery = z.object({
    limit: z.int().gte(1).lte(50).optional().default(8)
});

/**
 * Response Get Recent Comments V1 Blog Comments Recent Get
 *
 * Successful Response
 */
export const zGetRecentCommentsV1BlogCommentsRecentGetResponse = z.array(zRecentCommentPublic);

export const zDeleteCommentV1BlogCommentsCommentIdDeletePath = z.object({
    comment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zDeleteCommentV1BlogCommentsCommentIdDeleteResponse = zMessage;
